lib/util/feature.js, test/feature.test.js
Avoids `JSON.parse` of large feature shards by seeking to individual feature entries.
=> Optimize feature parse from JSON shard storage

index.js, lib/context.js, lib/geocode.js, lib/indexer/indexdocs-worker.js, lib/indexer/indexdocs.js, lib/util/feature.js, lib/util/relev.js, lib/verifymatch.js, package.json, test/feature.test.js, test/relev.test.js
Corresponding PR for carmen to https://github.com/mapbox/carmen-cache/pull/8.
Main substantive change is dropping of string `dbid`/`dbname` attributes from any relev objects, as these are not easily encoded into integers. Instead, the `dbidx` takes on the role of these fields.
=> [big-pants] relevnum

lib/indexer/indexdocs-worker.js, lib/indexer/indexdocs.js, test/index.test.js
Limits tile-cover list to 10k at indexing time. Also adjusts error handling of index-workers to be non-fatal so they can be tested more easily.
=> Limit tile-cover length to 10000

lib/index.js, lib/indexer/indexdocs-worker.js, lib/indexer/indexdocs.js, test/cache.test.js, test/indexdocs-worker.test.js
New feature: if you provide a `geocoder_tokens` key when indexing, it will be used to generate a fully condensed version of document when indexing. Saves us work on the source data side -- no more need to manually do this.
Current:
geocoder_tokens: { 'Street': 'St' }
document text: "Main Street"
indexed as: "Main Street"
document text: "Main Street, Main St"
indexed as: "Main Street", "Main St"
Example:
geocoder_tokens: { 'Street': 'St' }
document text: "Main Street"
indexed as: "Main Street", "Main St"
Will do some testing before mergetown + release.
cc @karenzshea @ingalls @sbma44
=> Generate token-replaced text when indexing

lib/index.js, lib/indexer/indexdocs-worker.js, lib/util/termops.js, test/index.test.js, test/indexdocs-worker.test.js, test/termops.test.js
Fixes an indexing bug introduced by https://github.com/mapbox/carmen/pull/202 where alternate condensed texts were not contributing to term frequency counts (and thus term weights in the phrase index).
Adds tests for `index.generateFrequency` as well.
=> Index token freq

test/context.test.js
^^ did the latest mapnik release switch `vtile.addGeoJSON` to use the geojson input plugin? Feels a bit not like a patch semver kind of change?
cc @springmeyer @flippmoke
=> Add geojson input plugin

lib/context.js, test/context.test.js
Require features returned from `vt.query` to fall within the 1000m tolerance bounds. This is required in carmen until https://github.com/mapnik/node-mapnik/issues/403 lands upstream.
Adds a test to demonstrate behavior failing currently in`master`.
=> Distance makes the heart

lib/geocode.js, test/geocode-unit.test.js
With upcoming changes to `carmen-cache` it'll be easier to stack indexes in a way where they provide identical results (e.g. both address points + interpolated addresses). In almost all scenarios it's not desirable to users to have feature results that are largely identical (e.g. by `place_name`).
This PR adds feature deduping by `place_name` with an `options.allow_dupes` flag that can be set to `true` if you really want those dupes.
=> Eliminate duplicate results based on identical place_name text

lib/geocode.js, lib/util/dedupe.js, test/dedupe.test.js
Address features may be dupes but not have identical place names. Abstract example:
100 main st springfield 00001 (exact address point)
100 main st springfield 00002 (interpolated point)
The place names differ because a result falls into another postal code area. These could be legitimately different addresses but in many cases they're the results of multiple results from datasets (interpolated vs exact, etc.)
In addition to deduping by `place_name` this branch adds deduping for features with `address` by `address + text` and a distance threshold of 10km as well.
cc @ingalls @karenzshea @sbma44
=> More aggressive deduping of addresses.

lib/util/termops.js, lib/verifymatch.js, test/geocode-unit.test.js, test/termops.test.js
At the moment carmen determines an address query based on the first addres-like token it encounters in a query.
This means that streets like `1 street 100` (where `100` is an address) fail as `1` is assumed to be the address. Using bitmasks prevents this as it exudes any of the currently matched text features from being used as an address.
=> Shady character (bitmask address lookup)

lib/indexer/indexdocs-worker.js
Instead of just printing the highest significant term, the debug flag now prints the weight of every token in a phrase. To enable `export DEBUG=1` before indexing. Results will be outdput to `STDOUT`
=> I'm Important Too!

lib/context.js, test/context.test.js
Currently features that are equally close to a query against a vector tile will be returned in whatever order they appear in the VT.
This PR alters this to be stable based on distance + `_id`.
=> donteverchange

scripts/carmen.js
Show feature ID, not just index name in carmen bin output.
```
Features
--------
- 1.00 Seattle, 98108, Washington, United States of America (place.98101)
```
=> Show id of feature results

lib/phrasematch.js, lib/util/cxxcache.js
Performance optimization: add another method for loading shards into memory without getting the results from the cache. Avoids a cpp => v8 object conversion which can be expensive for large sets.
=> cache#loadall

lib/index.js
These cases only need shards loaded and don't make use of the results of getall anyway. Speeds up indexing!
=> Use loadall when indexing

lib/phrasematch.js, test/geocode-unit.early-degen.test.js
The autoc work switched from using degens everywhere to only using them for the last term.
This pulls that approach back slightly, using the *closest* degen for every non-terminal term. So the closest matching term is used for every term except the last which is matched against a broad swath of possible matches.
=> Use closest (1) degen for non-terminal terms

lib/verifymatch.js, test/verifymatch.test.js
Extension of fix here: https://github.com/mapbox/carmen/pull/272.
Adds `_position` attribute to all feature docs internally to retain spatialmatch sort from cpp land. Some subtle relevance differences are lost in the `Relev => num` encoding between cpp and js land that we can still retain by keeping sort order stable.
=> Retain spatialmatch sort in final feature/context sorts

lib/verifymatch.js, test/verifymatch.test.js
Another stopgap fix. Scenario:
- proximity: NYC
- address A: address of type cluster in Georgia
- address B: address of type range in NYC
A would beat B even though B is very close to location bias.
Fix moves the cluster vs range and omitted sorts after distance sort.
Note score is still before distance -- we'll still want to establish a combined heuristic soon.
------
cc @ian29
=> Approximity2

lib/pure/applyaddress.js, lib/util/dedupe.js, test/address.nearest.test.js, test/address.test.js, test/dedupe.test.js
Prioritize cluster addresses over interpolated and gappy at dedupe time, rather than relying on feature sort order (fickle and influenced by proximity and other things).
=> Smarter dedupe

lib/context.js, lib/verifymatch.js, test/geocode-unit.score.test.js
This change alters the way `lib/verifyMatch.js` handles ghost features.
1. @aaronlidman introduces ['ghost' features](https://github.com/mapbox/carmen/commit/906b025c9dadba8a7decc10cca301c1e47fa5c18) for alt places - [relevant devlog](https://github.com/mapbox/hey/issues/1825)
2. @yhahn allows ghost features to be [returned in context array](https://github.com/mapbox/carmen/pull/253)
- A ghost feature will never be returned in a reverse geocode
- A ghost feature can be returned in a context array _if_ the input query matches the ghost feature text
- scored feature
```
query:  7449 E River Rd Fridley
result: 7449 E River Rd Fridley
```
- ghost feature
````
query:  7449 E River Rd Minneapolis
result: 7449 E River Rd Minneapolis
````
(these are the same feature)
- A ghost feature can never …
=> Ghost in the machine

lib/spatialmatch.js, lib/util/proximity.js, lib/verifymatch.js, package.json, test/geocode-unit.scoredist.test.js, test/proximity.test.js, test/verifymatch.test.js
When in proximity mode:
**master**
- Find most relevant results, then rank them by distance to the proximity point
- At the final stage of verifymatch sort by score, index type, then distance
Concretely this leads to it being very difficult to find the highest scored feature named `NNN` if you are closer to other features named `NNN`.
Example: from Washington DC, there are San Francisco's in Colorado, Colombia, El Salvador, and Venezuela that are all closer to DC than San Francisco in California (and thus outrank it).
**closetomyheart**
- Find most relevant results, then rank them by a combined score + dist heuristic score called `scoredist`. This converts each feature distance to a number that is appropriate for comparison against scores using a [basic …
=> scoredist (score + distance heuristic) for proximity

lib/util/token.js, test/geocode-unit.unicode-replace.test.js, test/replace.test.js
Creates a second token replacement pair when the original token replacer unidecoded differs from itself.
Example -- you define a token replacement pair like:
'Maréchal': 'Mal'
This will catch input docs with text like `Maréchal` but miss input docs or input queries with text like `Marechal`. Token replacement now defines the second pair automatically for you when it creates the replacer object.
'Maréchal': 'Mal',
'Marechal': 'Mal'
Note that this is different from the previous behavior which unidecoded *everything* once and expected the input text to be unidecoded as well -- which had totally horrible autocomplete behaviors.
------
This is a borderline breaking change because previously generated indexes will have missing contracted phrases but going to treat it more like a very severe …
=> Unidecoded token replacement pairs

lib/phrasematch.js, lib/spatialmatch.js
We're currently loading grids for all phrases that exist in indexes at `phrasematch`. This is a little crazy though -- immediately after `phrasematch` we build potential subquery stacks and then [carefully pick the best ones to spatialmatch](https://github.com/mapbox/carmen/pull/302), throwing out a bunch of subquery stacks that don't make the cut. At the end of this process we'll have the same or fewer phrases to consider.
This moves grid loading to immediately before spatialmatch when we know exactly what we'll be evaluating.
The I/O gains atm are modest currently (10-20%) but as we get more efficient with the number of stacks evaluated in the future these gains will increase (https://github.com/mapbox/carmen/blob/master/lib/spatialmatch.js#L11).
=> Load grids at spatialmatch phase

lib/util/proximity.js, test/proximity.test.js
The proximity zxy needs to stay within the unsigned integer space as it's hopping over to unsigned ints here https://github.com/mapbox/carmen-cache/blob/master/src/binding.cpp#L792.
Enforce this at the carmen input level.
Refs https://github.com/mapbox/geocoding-example/issues/2
=> Smallworld

lib/verifymatch.js, test/geocode-unit.strictloose.test.js
Fixes a bug where certain query + context stacking combinations are scored lower than they should be at the final context relevance calculation. Example:
albany australia
Which matches the following context:
albany, western australia, australia
Should receive a relevance of `0.99+` as all query terms are matched between `albany` and `australia`. However in `master` this feature can mistakenly receive a lower score as the context verification can use `albany` and `western australia` (query is missing `western`, so some penalty is applied).
This branch runs the context relevance calculation twice -- once in strict mode (using only the features in the matching spatialmatch stack) and once in loose mode (using all matched spatialmatch stack features) and then uses the higher of the two …
=> Strictloose

lib/verifymatch.js, test/geocode-unit.score.test.js
Smartly dedupe ghost features out of a result set when there are real features with the same text in the same resultset.
=> Ghostblogger

README.md, lib/geocode.js, lib/verifymatch.js, package.json, test/geocode-unit.proximity.test.js, test/geocode-unit.types.test.js
This adds an optional `options.types = [ <type>, <type>, ... ]` query option for filtering results to only the types specified. By default all types are allowed.
- This will bump carmen to 5.2.x
- Affects both forward + reverse geocodes
- Adds tests + documentation for this feature to the README
cc @sbma44 @ian29 @ingalls @camilleanne
=> Optionally filter results by feature type

test/termops.encodePhrase.test.js, test/termops.encodeTerm.test.js
Got pwned in refactoring. Lockdown our knowledge of collision rates via test assertions.
=> Add tests to assert collision rates of encodeTerm, encodePhrase

lib/verifymatch.js, test/geocode-unit.proximity.test.js
Rather than max for calculating `scoredist`. Allows outlier high-scorers to beat closeby features until you're really close.
=> Use geometric mean of feature scores

.retireignore, lib/util/termops.js, lib/verifymatch.js, test/geocode-unit.address-alphanumeric.test.js
Tightens up regex criteria used to match tokens as address numbers on address range features. In particular `1A` will continue to match but `1AB` will not. This is necessary to properly support UK postcodes -- e.g. `B77 1AA` -- when loaded alongside range features like `B77 ###`.
@yhahn would to hear your sense on whether included tests are adequate.
=> stricter address num criteria

README.md, index.js, lib/context.js, lib/geocode.js, lib/util/addfeature.js, lib/util/ops.js, lib/util/proximity.js, test/fixtures/mem.json, test/geocode-unit.address-format.test.js, test/geocode-unit.early-degen.test.js, test/geocode-unit.fnv1a-collision.test.js, test/proximity.test.js
Captured from chat
```
ingalls [22:09]
unintended side affects
basically really really early on the geocoder_address flag is used to determine if phrasematch should generate address permulations for a given source
for most layers this doesn’t really matter
as places/regions etc
don’t have numbers in them
heyitsgarrett [22:09] 
right
ingalls [22:09] 
so the address permutations fail and are then ignored
for postcode however
the address permutations ​_can_​ be generated
as a number is found
that is a potential housenumbers
but when it goes back to actually look up this permutation in the index
it can’t find a housenumber that matches
because the postcode indexes don’t have the additional housenumber info
which results in the postcode index hard failing and returning no results
```
cc/ …
=> Versions Are Cheap geocoder_format

index.js, lib/context.js, package.json
applies two strategies for controlling memory consumption:
- adjustable vector tile cache size
- moves `ldict` cache in `carmen-cache` -- used for pre-I/O feature existence checking by ID -- to a 32 bit space by truncating the full 64 bit ID
=> slimmer caches for testing

README.md, index.js, lib/context.js, lib/geocode.js, lib/util/ops.js, lib/verifymatch.js, package.json, scripts/carmen.js, test/context.test.js, test/geocode-unit.address-format.test.js, test/geocode-unit.language-flag.test.js
Adds the ability to pass a language flag (an iso language code verified by [model-un](http://github.com/mapbox/model-un)) to Carmen.
https://github.com/mapbox/carmen/pull/319 paves the way for queries in local languages, this opens up returning a response in a specified language when available in the index. Defaults to whatever is in `carmen:text`.
Also supports custom templates in indices by language, e.g. `"geocoder_format_zh": "{country._name}{region._name}"`
to do:
=> add language flag

lib/util/termops.js, test/geocode-unit.localtext.test.js
Throw an error if you try to build an index with bad language tags.
=> Don't allow invalid language codes to be indexed

lib/context.js, lib/geocode.js, lib/util/ops.js, test/geocode-unit.address-format.test.js, test/geocode-unit.language-flag.test.js
only use the localization template when there are response elements in that language.
This PR acknowledges some odd edge cases that might be encountered now that true localization is supported:
1. Indices with a local template, but no corresponding localized text for the response feature, or any feature in the response context.
_Will return the default text with the default template as `place_name`._
2. Indices with a local template, but no corresponding localized text for the response feature, but has a context item with localized text.
_Will return `place_name` formatted with localized template with either default or localized text as available._
3. Indices without a local template for the most specific response feature, but localized text/localized templates for context features.
_If …
=> Appropriate localization templating

bench/dictcache.js, lib/util/dictcache.js
Bench comparison:
dictcache.Dictcache
Dictcache x 777 ops/sec ±3.89% (82 runs sampled)
dictcache.Dictcache
Dictcache x 1,629 ops/sec ±4.39% (82 runs sampled)
=> Dumber faster

lib/util/dictcache.js, test/dictcache.test.js
When not specified, autodetect it. Smooths out some operations!
=> Autodetect dictcache bitsize from buffer length

lib/context.js
And add a little logic to handle center attributes from VT encoders that JSON-encode arrays.
=> Simplify/robustify how context handles center, text properties

lib/context.js
Will merge when tests pass.
cc @ingalls
=> Remove deprecated text properties from context

lib/context.js, lib/util/ops.js, package.json, test/context.test.js, test/fixtures/context-vt-light.json, test/ops.test.js
Country codes are a common feature request for geocoding. These are easy enough to expose in an country document's custom properties. However, it will often be desirable to understand the country that a non-country-level result resides in. Doing so will require more information to be exposed in a result's `context` array.
This PR exposes the `iso3166` custom property of `country` objects in a result's `context` array (when it exists).
This is a straightforward implementation and follows the precedent of hardcoding which properties get exposed in `context`. But I'm not sure it's the best or most flexible approach. 
An alternative would be to define a new Carmen GeoJSON property that indicates which properties should be exposed in `context`. For example:
```
properties: {
"carmen:center": …
```
=> expose non-carmen properties in context array

lib/util/addfeature.js, package.json, test/context.test.js
node-mapnik@3.4.10 brings in Mapnik v3.0.9-rc2 which has improved GeoJSON parsing behavior in the sense that it is stricter. This caught a few things which likely should be fixed in general. Companion pull request to #372
=> Node mapnik 3.4.10

index.js
Indexing-only sources, for example, do not have this method.
cc @camilleanne
=> getGeocoderData is also optional

circle.yml, lib/index.js, lib/indexer/indexdocs-worker.js, lib/indexer/indexdocs.js, lib/phrasematch.js, lib/util/bitcache.js, lib/util/dawg.js, lib/util/termops.js, package.json, test/dawgcache.test.js, test/index.test.js, test/indexdocs-worker.test.js, test/termops.encodePhrase.test.js, test/termops.getIndexablePhrases.test.js
This rolls back the phrase-as-object concept bringing `yo-dawg` a bit closer to `master`. (https://github.com/mapbox/carmen/compare/yo-dawg-patchtext)
I'm realizing the reason I knee-jerked in this direction is because at runtime we already have the `subquery` object that serves a very similar concept to the phrase object currently in the `yo-dawg` branch.
Should pass tests locally -- not passing on circle for build-ey reasons.
cc @apendleton for your review
=> [yo-dawg] Unobject encodePhrase

bench/replaceTokenGroups.js, lib/util/token.js, package.json, test/replace.test.js
Enables named group replacement in token substitutions, employing xregexp to support it.  For performance reasons, uses existing regexp functionality when named group replacements aren't needed. 
note: when a named replacement group is used in a replacement pattern, the regex pattern must not contain any numbered/un-named groups (an error will be thrown if it does). This is necessary in order to avoid some very confusing substitution-group-renumbering scenarios.
also note that xregexp is pinned because an internal structure is used to simplify the process of detecting whether a pattern contains named groups.
=> use xregexp for named token group replacement

lib/util/addfeature.js
At the moment the `addFeature` function used by our unit tests overwrites the vector tiles each time it is called. This is fine for forward only indexes as these are appended to. However for reverse queries it causes problems as only the last feature will be present.
This PR changes this behavior to retain all features in a given VT.
=> Allow adding multiple features

lib/api-mem.js, lib/spatialmatch.js, test/geocode-unit.io-stack.test.js
- Adds io logging to the memsource for logging + testing io for different query scenarios,
- Adds tests to demonstrate that in master it's possible to load the same grid cache shard multiple times during the same query (https://circleci.com/gh/mapbox/carmen/343),
- Adds logic to spatialmatch to dedupe I/O for loading grid cache shards
=> Dedupe spatialmatch cache loading I/O

lib/verifymatch.js, test/geocode-unit.geocoder_stack.test.js
@sbma44 discovered a bug in the stack filtering code. If a highly scored feature not part of a desired stack was filtered out of the results, the parallel array of metadata would be off by one and match incorrectly.
This is easily fixed by ensuring filtering removes the array element from both the features array as well as the metadata array.
=> Iratus Bug fix

lib/geocode.js
- Enforce max query length of 256 chars
- Enforce max token length of 20 tokens
- Unit tests
cc/ @karenzshea @yhahn @ianshward
=> Ensure query lengths don't cause stack errors

lib/indexer/indexdocs.js
I know, I know, the realistically it's just a best practice and not a bug. Just something that immediately catches my eye when reading Javascript.
In `index-worker.js` around line 162 there is `if (zxy[1] < 0 || zxy[2] < 0) continue;`. In the whole `load_docs` subroutine any data that looks off is either handled by a warning and/or early exit. I'm surprised in that line faulty input is skipped silently. (Of course negative tile number and zoom levels shouldn't ever happen to start with).
In `scripts/carmen.js` there is `('  --proximity="lat,lng"   Favour results by proximity');`. It should say `lng,lat`.
The `termops.getIndexablePhrases` is only called in one place. It returns an array of strings. Right after the caller checks for duplicate entries. Wouldn't it make more sense if the …
=> != vs !===

package.json
Don't run carmen tests twice with different dictcache env vars; those don't do anything anymore
@yhahn can you confirm that this is kosher?
cc @ingalls
=> Only run tests once

lib/index.js
Inside `indexDocs()` there's a `console.timeEnd` which fails if this timer was never started.
=> make sure timer for getIndexableDocs gets started

package.json, test/index.test.js
This updates carmen-cache, and removes one carmen test that assumes no-longer-present dict functionality in carmen-cache now that dict is gone (and also assumes that "stat" is sharded, which it no longer is).
=> Bump carmen-cache to 0.11.2 and remove test that depends on hasDict

lib/indexer/indexdocs.js, test/index.test.js, test/indexdocs.test.js
Carmen will fail if you attempt to index features that do not have a center set.
From chat with @ingalls:
>ingalls [4:13 PM] 
@sbma44: @mattficke Carmen won’t actually generate centres
it will only correct them if there are invalid centres
so the centre column has to be populated with a valid lon/lat coord
or else it will hard fail
We should consider changing this as carmen’s centres are perfectly fine
This check seems to be redundant and causes unnecessary failures since we also check for and fix the center with this code:
```js
if (!doc.properties["carmen:center"] || !verifyCenter(doc.properties["carmen:center"], tiles)) {
console.warn('carmen:center did not fall within the provided geometry for %s (%s). Calculating new point on surface.',
doc.id, doc.properties["carmen:text"]); …
```
=> remove check for carmen:center at load time

lib/util/dedupe.js, test/dedupe.test.js
Dedup  using lowercase version of address so that
`20 DUMBARTON CRESCENT` and `20 Dumbarton Crescent` are treated as equals.
=> Dedup between different cases

lib/indexer/indexdocs.js, lib/pure/addresscluster.js, test/geocode-unit.address-alphanumeric.test.js
Currently address clusters are retained as they are submitted to carmen. So if `24A` is submitted in a cluster it remains `24A`, `24a` remains `24a` etc. The input however is always lowercase. Since the way these are matched up is simply a javascript array, if there is a case different, a match doesn't occur.
`["24a", "24A"]`
This PR ensures that both the query address and the address cluster array are always lowercased.
cc/ @yhahn @sbma44
=> Address cluster CAPS

lib/indexer/indexdocs.js, test/fixtures/indexdocs.parseDocs.json, test/indexdocs.parseDocs.test.js
Test-only changes for demonstrating what `indexdocs.parseDocs` does on `master` now for comparison with upcoming changes.
=> Add tests for indexdocs.parseDocs

lib/indexer/indexdocs.js, lib/util/addfeature.js, test/fixtures/indexdocs.parseDocs.json, test/geocode-unit.score.test.js, test/geocode-unit.stacky.test.js, test/indexdocs.parseDocs.test.js, test/indexdocs.test.js
Removes interpolation properties from point address features and vice versa in vector output.
=> Strip unused address properties from vector output

lib/context.js, lib/geocode.js, test/context.test.js, test/geocode-unit.limit.test.js
Turns out the types/limits flow was already loading features per need in https://github.com/mapbox/carmen/pull/503. This PR does some cleanup/refactoring to make this clearer.
- `types + limit` reverse query mode is now only a concept handled by `reverseGeocode()`.
- `context()` always returns a single context.
- Adds `context.nearest()` for playing the role that the proximity context mode played before -- returns a flat array of `[ lon, lat ]` points that can then be `context()` queried for full features.
- Adds additional unit test to demonstrate that in types/limits mode reverse geocodes do indeed load full features/derive address points properly.
cc @ingalls for the review
=> Refactor types/limits code flow + requirements

scripts/carmen.js, test/bin.test.js
builds on @ingalls' excellent idea, but goes for the full `JSON.stringify` now that we are debugging implementations that rely more heavily on feature scores and don't want them hidden away as `[ Object ]`s. Cleaned up formatting a little bit while I was at it.
=> make `--debug` more verbose

scripts/carmen-index.js
Writes to `process.stdout` aren't necessarily blocking, so calling process.exit() can sometimes end the process before indexing has finished. This change allows `process.stdout` to finish before exiting.
Node documentation reference: https://nodejs.org/api/process.html#process_process_exit_code
Many thanks to @ericfischer for assistance tracking this down.
=> Let process.stdout finish before exiting

lib/spatialmatch.js
Removes last of our `push.apply()` ways of adding onto arrays.
=> Don't use push.apply to avoid max call stack errors

lib/spatialmatch.js, test/spatialmatch.stackable.test.js
- Pass in the stacks array and build it up directly rather than using `.concat()` or `push.apply()` to join 2 arrays. This cuts down on array/object creation on deep permutation trees with a significant speedup.
- Optimize several checks.
=> Optimizations for spatialmatch.stackable()

lib/verifymatch.js
Fixes what looks to be a typo in verifymatch introduced in https://github.com/mapbox/carmen/commit/b83135caa713094229fd644864cef1a5915d2c64 .
cc @yhahn
=> Fix probable typo in verifymatch

lib/verifymatch.js
Not all feature loads succeed, example:
https://github.com/mapbox/carmen/blob/master/lib/util/feature.js#L204-L207
This fix guards against this by skipping unloaded features.
=> Guard against feature load misses

lib/util/filter.js, test/filter.test.js, test/geocode-unit.multitype.test.js
Needed to ensure a query like `caracas?types=place` works when the feature needs to come from the region index.
=> Fix type filtering for multitype indexes on forward geocodes

lib/spatialmatch.js, test/spatialmatch.stackable.test.js
For a given set of phrasematches, `spatialmatch.stackable()` generates all the possible/allowed stacking permutations that we should consider as potential geocoding matches in the real world.
**Simplified example:** If we matched
```
100 main street (poi)
100 main street (address)
new york (city)
new york (state)
```
Stackable says we need to check for:
```
100 main street (poi)
100 main street (address)
new york (city)
new york (state)
100 main street (poi), new york (city)
100 main street (poi), new york (state)
100 main street (address), new york (city)
100 main street (address), new york (state)
```
Then would sort these in order of most likely relevance.
------
With long queries that match many possible phrases across a lot of indexes, this list of permutation grows exponentially and …
=> Benchmark and further optimize spatialmatch.stackable()

package.json, test/fixtures/output.dev.geojson
Skipping review because the underlying changes were already reviewed in the carmen-cache pr.
=> fix #540 with more deterministic sort in carmen-cache

lib/indexer/indexdocs.js, lib/util/feature.js, test/indexdocs.test.js
- switches from returning strings for errors to throwing exceptions
- cleans up a couple minor things like string concatenation and long lines
---
=> use exceptions instead of string return values for error handling

lib/context.js, lib/util/ops.js, test/geocode-unit.promote-language.test.js
**The problem:**
- The goal of `squishy` was to be able to promote a feature like `New York (place), New York (region)` past `New York (region)` on the basis of its text matching its parents.
- When localization is introduced, there's some ambiguity about what ^^ means. Is the text supposed to match between localized versions? Non-localized versions? What if there's some mixture of scripts or language because of language fallback handling?
- Currently in `master` you can lose the effect of the `squishy` adjustment when using the `language:` option because `context()` is resolving the localized version of `carmen:text` early, but the top feature in the stack is being resolved late.
**The fix:**
- `context()` is going to pass all `carmen:text*` properties onto the caller. It's the caller's …
=> context: Defer language resolution

lib/indexer/indexdocs.js, test/index.test.js, test/indexdocs.test.js
Carmen `master` currently throws when a feature's ZXY tile cover list exceeds 10k features. This is a hard limit put in place to make sure
- grid cache sizes don't blow up too large
- carmen-cache's `spatialmatch` performs reasonably well
On the flipside, this limitation has forced us to come up with various half-measures for indexing very large polygon features (e.g. huge features in northern Canada or Russia that get gigantized by Web Mercator).
------
We'd make use of [multi-zoom tile covers](https://github.com/mapbox/tile-cover#polygons) to reduce the size of the zxy list. There are a lot of challenges in the path to doing this, however.
This branch implements a carmen-level stopgap:
- Warn when we hit a feature with 10k tile covers
- Sort the tile cover list prioritizing covers …
=> Stopgap handling for features with > 10k zxy's

index.js, lib/geocode.js, lib/phrasematch.js, lib/spatialmatch.js, lib/util/dawg.js, lib/verifymatch.js, package.json, test/dawgcache.test.js, test/fixtures/output.dev.geojson, test/geocode-unit.debug.test.js, test/spatialmatch.rebalance.test.js, test/spatialmatch.stackable.test.js
this does two things:
- splits some source-level properties (`loadall`, `getter`, `nmask`, `bmask`) into a separate object to make it clearer that they are source-level and to avoid things like [picking a value off of the first phrasematch](https://github.com/mapbox/carmen/blob/7150b4adf4c81b41deb832ef6e38349120d84714/lib/spatialmatch.js#L188)
- adds classes for `Phrasematch` and `PhrasematchResult` so that they are more clearly and rigidly defined
The main changes are in `lib/phrasematch.js`. All the other changes are just adapting to that.
---
motivation:
One of the more confusing things about carmen right now is understanding what type an object is and what properties it has. Sometimes the members of an object are added in multiple places …
=> add Phrasematch and PhrasematchResult types 

README.md, index.js, lib/verifymatch.js, test/geocode-unit.promote-language.test.js, test/geocode-unit.promote-on-identical-name.test.js, test/geocode-unit.promote-score.test.js, test/geocode-unit.types.test.js
- Switch score inheritance from opt-out to opt-in on a per index basis to make this feature 100% optional: `prevent_promotion => geocoder_inherit_score`
- Compares `carmen:text` and all `carmen:text_{language}` strings (between the same language codes) for the target and candidate features.
- Considers text matching if target text is fully present as a substring of the candidate text.
Functionally this helps cover cases like:
- Bern (city) within, Canton of Bern (administrative region)
- Requires substring text match between candidate + target
- Inconsistent use of `carmen:text` (known issue where the language is often indeterminate/inconsistent) making one or more of the `carmen:text_{language}` properties often more suitable for consistent/robust comparison
- Requires considering all …
=> Score inheritance (v3)

CHANGELOG.md, lib/index.js, lib/phrasematch.js, lib/util/termops.js, package.json, test/geocode-unit.emoji.test.js, test/termops.encodableText.test.js
We previously failed to properly decode emojis, but our character set check resulted in these queries becoming `'x'` instead of `''` after decoding. 
This PR:
- Checks the length of the text after the character check, and returns `''` for un-decodable text.
- Tests for correct behavior
- Tidies up some docstrings and a variable name.
Fixes https://github.com/mapbox/api-geocoder/issues/1129
=> Handle Un-decodable Text like Emojis

lib/context.js, test/context.stackFeatures.test.js, test/geocode-unit.multitype-leapfrog.test.js
Handle cornercase in multitype promotion where the feature to by promoted skips one or more levels of hierarchy. Example:
Layer hierarchy:
- region
- district
- place
Overlapping Feature A:
- text: `Icecream Citystate`
- types: region, place
Overlapping Feature B:
- text: `Strawberry District`
- types: district
On a reverse geocode, currently `Strawberry District` will beat `Icecream Citystate`. This is a bug, since `Icecream Citystate` _can_ be promoted to a more specific type than `Strawberry District`, but currently `carmen` is not handling this case.
This PR fixes this issue by considering the most specific promotion possible and comparing to other features' types, allowing more specific promotions to beat those features.
=> Fix bug for multitype promotion across types

lib/util/closest-lang.js, test/closest-lang.test.js, test/geocode-unit.language-flag-bogus.test.js
Currently in master, an unmatched language suffix triggers immediate fallback to the next available language, e.g.:
```
Available data:
en, es, fr, de
Requested language:
en-xx => (unmatched, triggers fallback to...) es
```
This PR adds additional handling to make sure that available "fuzzy" language code matches are respected (`zh-hant`, `zh_Hant`, `zh_HANT`, etc. all collapse to the same value) but unknown suffixes first search for a language-only value before proceeding to fallback languages.
```
Available data:
en, es, fr, de
Requested language:
en-xx => (unmatched, first checks for language-only value) en
```
=> Robustify language fallback for unmatched suffix

lib/util/ops.js, test/geocode-unit.text-trim.test.js
Data is messy. Carmen doesn't do a ton of automated cleanup but whitespace at the front/back of text values seems simple enough to do safely.
- Unit tests for preceding/trailing whitespace in source data
- Assertions check that `text`, `place_name` and context feature `text` all get whitespace cleaned up
- Checks ^^ for language-specific values
- Implements whitespace trimming
=> Trim whitespace from text values

package.json, test/fixtures/output.default.geojson, test/fixtures/output.dev.geojson, test/fixtures/output.reverse-dev.geojson
Updates to carmen-cache@0.14.1 which includes optimizations for the spatialmatch `coalesce()` step. Refs https://github.com/mapbox/carmen-cache/pull/65
=> Use carmen-cache@0.14.1

package.json
The `eslint` module is 26 MB once installed. It should be installed as a devDep to avoid increasing the size of  `npm --production` installs unnecessarily.
=> Move eslint to devDeps

lib/geocode.js, test/geocode-unit.geocoder_stack.test.js
Folks were using capital letters in the `options.stacks` array. Since the stacks filtering is typically used for country level filtering, these do not need to be base sensitive.
- Add `toLowerCase` to all elements of `options.stacks` array.
- Add associated tests
=> Iterate through options.stacks array - lowercasing & add tests

package.json, test/geocode-unit.debug.test.js
Updates to carmen-cache@0.15.0 with a more robust `coalesce()`. See https://github.com/mapbox/carmen-cache/pull/66 for full details.
This will start carmen @ 17.8.x
=> carmen-cache@0.15.0

lib/util/closest-lang.js, test/closest-lang.test.js
The langauge fallback code didn't work if the language existed as a feature property with a null value.
Fixes #565
=> Handle null language values

lib/verifymatch.js, test/geocode-unit.jp-order.test.js, test/geocode-unit.order.test.js
Ensure that bumps can cancel each other out so score can be the deciding factor.
=> Cancel bump

lib/indexer/indexdocs.js, test/geocode-unit.zeroscore.js
When using carmen backed by mbtiles, with a configured `maxscore` property with a value of 0, a subtle indexing bug can occur whereby the `maxscore` property is read out of the `.mbtiles` file as a string instead of a number, and is consequently interpreted as truthy rather than falsy, causing some intended protections against divide-by-zero to fail.
This PR ensures that source.maxscore is cast to an integer before using it in calculations, and adds a test to make sure this behavior continues to work.
=> Fix indexer behavior for indexes where the max score is specified as 0

carmen-geojson.md, lib/context.js, lib/geocode.js, lib/util/ops.js, test/context.stackFeatures.test.js, test/context.test.js, test/fixtures/output.default.geojson, test/fixtures/output.dev.geojson, test/fixtures/output.reverse-dev.geojson, test/geocode-unit.address-format.test.js, test/geocode-unit.multitype-leapfrog.test.js, test/geocode-unit.multitype-reverse.test.js, test/geocode-unit.multitype.test.js, test/ops.test.js
This softens the behavior of the previous PR adding multitype behavior (https://github.com/mapbox/carmen/pull/529) and adds the `place_type` key to provide better visibility into multitype features in response data.
- If a multitype feature and other normal features may be returned for the same type level for a given reverse geocode, the normal features will take precedence. This changes the previous behavior where a multitype feature would override other features at the promoted level.
- Include new `place_type` property for enumerating all the possible types of a returned feature. Usually this is an array of just one element -- the type of the feature.
=> Multitype backfill + place_type

lib/analyze.js, lib/index.js, lib/spatialmatch.js, lib/util/cxxcache.js, package.json
A slew of fixes + performance improvements from @springmeyer upstream in `carmen-cache`.
Since this changes our indexer (makes sense given the perf improvements that shards must be unloaded before being loaded again to be fresh) I'd like to do some IRL indexing testing to make sure all of this is :ok_hand:.
=> @mapbox/carmen-cache@0.16.2

lib/util/termops.js, test/termops.tokenize.test.js
If a string loosely fit the format of a reverse query `Number , Number` it could be interpreted as such even when actually being a forward query.
This was due to `parseFloat` ignore non-numeric characters and just grabbing any number it sees.
Ref: https://github.com/DenisCarriere/geocoder-geojson/issues/8#issue-201756354
=> Use Number for hard error on non-numeric input

scripts/carmen.js, test/bin.test.js
The `--stats` flag reports the timing of each major operation: `warmup`, `phrasematch`, `spatialmatch`, and `verifymatch`.
The `warmup` value was broken: It was reporting a date rather than a delta. Looks like this went missing in https://github.com/mapbox/carmen/commit/9d78a3115d01be874bc6ed1b77c2976c12ae67b3
This fixes the `warmup` value by ensuring it represents elapsed time.
Do we need tests of the command line tools like `scripts/carmen.js`?
=> Fix stats output for scripts/carmen.js

lib/phrasematch.js, lib/util/termops.js
I profiled the [setup routine](https://github.com/mapbox/carmen/blob/master/bench/geocode.js#L13-L50) and [geocode routine](https://github.com/mapbox/carmen/blob/master/bench/geocode.js#L64-L69) of `bench/geocode.js`.
With the `setup` routine I noticed:
- The main event loop was quite busy (98% of time sampled it was busy in sync code)
- The threadpool was idle
- The primary bottlenecks in the main event loop were: 1) garbage collection, 2) `unidecode`, and 3) v8 string and array manipulation
- The main bottleneck within `unidecode` was string allocation, deallocation, and `std::string::append`. 
With the `geocode` routine I noticed:
- The main event loop was fairly busy (77% busy, 23% idle)
- The threadpool was idle (with the exception of < 1 % in `carmen::cache::coalesce`)
- The …
=> Optimize phrasematch

lib/spatialmatch.js, lib/util/ops.js, test/geocode-unit.spatialmatch-stack-truncate.test.js, test/ops.test.js
Some queries from in IRL (whether intentional or from garbage mishaps like double copy + paste) can lead to very deep, legitimate subquery stacking combinations like:
```
['Pizza Shop', '100 Main St', 'Springfield', 'Massachusetts', 'United States', 'N Main St', 'Springfield', 'Massachusetts', 'United States']
```
These currently are a real performance killer and unnecessarily so. For now this PR implements truncation of long subquery stacking combinations, grabbing only the 4 most specific subquery features to match at the coalesce stage.
- Adds tests for this in both the ascending and descending specificity direction (e.g. to make sure we handle CJK general => specific ordered queries correctly)
- Interestingly even if we truncate subquery stacks **some final results end up with > 1.0 …
=> Truncate subquery stacks to top 4 elements

package.json
Update to carmen-cache@0.16.4 with a key bugfix (https://github.com/mapbox/carmen-cache/pull/82) that affects longer queries.
=> Use carmen-cache@0.16.4

README.md, index.js, lib/util/closest-lang.js, lib/util/feature.js, lib/util/filter.js, lib/util/ops.js, test/closest-lang.test.js, test/filter.test.js, test/geocode-unit.languageMode-universal.test.js
Following on the heels of the `languageMode: strict` option (https://github.com/mapbox/carmen/pull/580), this PR provides a `geocoder_universal_text` option that allows an index's text to be treated as compatible with any/all languages. The most immediate use case is for postcodes (e.g. the zip code 10000 need not be translated into any other language) though there may be other uses in the future.
This index-specific flag was easiest to implement as a post-feature/context load modifier. If an index sets this flag to true, all features going through the `feature.normalize(source, properties)` function will have its `carmen:text` field copied to `carmen:text_universal`.
The remaining steps were to make sure the closest language/language filtering logic respected a `carmen:text_universal` …
=> Add geocoder_universal_text flag

lib/util/fallback.json, test/closest-lang.test.js
The Serbian language can be written with either Latin or Cyrillic script. This sets to fallback for region-specific Serbian language codes to prefer Latin script.
* Add `sr_Latn` fallback for `sr_BA`, `sr_CS`, `sr_ME`, and `sr_RS` codes
=> Serbian script preference

lib/util/closest-lang.js, lib/util/equivalent.json, lib/util/filter.js, test/closest-lang.test.js, test/filter.test.js, test/geocode-unit.languageMode.test.js
Follow-up to #593 & #594. Excludes languages with subtypes that use varying scripts from falling back to a potentially mixed-script result.
* Add a `digraphic` array of languages known to use multiple scripts
* For these languages, don't attempt a loose match in strict languageMode.
=> exclude loose language matches known to involve mixed scripts

lib/indexer/indexdocs.js, test/indexdocs.test.js
Javascript comparison operators handle the value `null` in a somewhat non-intuitive manner:
```sh
> null == 0
false
> null > 0
false
> null >= 0
true
```
As a result, in certain edge cases a null value in a feature's `carmen:center` property can sneak past the `verifyCenter` check when the feature exists on a tile abutting the equator or the prime meridian.
* Check for null values in `verifyCenter`
=> handle null center coords

lib/util/dawg.js
@sbma44 had an issue with an index build where the DAWG construction was failing. I was pretty sure this was a sorting problem post-unidecode, in which in certain corner cases, strings containing complex characters might sort character-wise differently than they do byte-wise. Strings were already bucketed by their first three characters, so most comparisons should already be apples-to-apples by script, but I think a corner case may exist when comparing strings that contain a mix of different complex scripts. We weren't actually able to pin down the specific string causing the failure, but this PR caused the index build to succeed.
Converts strings to buffers before sorting, and then sorts using the `Buffer.compare` sort function.
=> Janky, but try sorting buffers instead of strings before dawg insert

lib/util/ops.js, test/geocode-unit.matching-text.test.js
Desired behavior:
- Include `matching_place_name` on a feature if any part of the query matches part of the result feature's context and adjusts the text to be displayed based on what the user typed (e.g. matching a synonym for part of the context)
- Example query/matching: **Kansas, Am**erica
- Canonical placename: Kansas, United States
- Include `matching_text` property on a resulting feature if the feature itself is where the canonical/matching discrepancy lies:
- Example query/matching: **Ameri**ca
- Canonical text: United States
This PR fixes up a few cases where this desired behavior ^^ was not being captured fully if 
`geocoder_format` was set.
=> Robustify matching text handling when geocoder_format is set

lib/util/feature.js, test/feature.putFeatures.test.js
During indexing, we [shard features](https://github.com/mapbox/carmen/blob/master/lib/util/feature.js#L188-L190) by a 20-bit integer derived from the feature ID. When retrieving features from their cover, we then look at the z/x/y coordinates of the returned features to pick the correct feature from that shard.
In rare cases, multiple features will share both the same shard ID and z/x/y tile coordinates, which can prevent a feature from being found in a forward geocode.
In cases when there are multiple features with the same z/x/y coordinates in a given shard, this adds an additional check that compares the feature score to the cover's score.
* Loop through all loaded features in `getFeatureByCover`
* When there are multiple matches, check the feature score and remove from results if they …
=> Avoid shard ID collisions

lib/util/remove-diacritics.js, test/diacritics.test.js
The arabic character "YEH" varies slightly in the Persian writing system, which causes some queries to miss.
| query for "tabriz" | unicode for "YEH"                | matches?   |
|:-------------------|:---------------------------------|:-----------|
| تبريز              | `U+064A ARABIC LETTER YEH`       | ✅          |
| تبریز              | `U+06CC ARABIC LETTER FARSI YEH` | ❌        |‎ |
New pattern replacements to `removeDiacritics` that collapse three variants of this character into the same character.
=> collapsing across variants of arabic YEH

package.json
Upstream tests were failing due to extraneious node-pre-gyp module. @apendleton tracked this down to cache pretest installing it in addition to package.json
Tag and merge upstream
=> carmen-cache@0.18.1

scripts/whitespace-analysis.js
The purpose here is to normalize a query and understand how often they overlap. The results are given as a percentage.
Young pulled us-address & us-place data for analysis.  I ran this test and found that less than 3% of this data overlaps at all. After looking at the detailed overlapping queries I found there were very few concerning points. The worst examples were: 
```
[
“1 1/2 Ave”,
“11/2 Ave”
],
[
“Ao Pl”,
“A O Pl”
],
[
“Le an St”,
“Lean St”
],
[
“Nace Ln”,
“N Ace Ln”
],
[
“Nace Rd”,
“N Ace Rd”
],
```
[ 632](https://github.com/mapbox/carmen/issues/632)
- [ 632](https://github.com/mapbox/carmen/issues/632)
[633](https://github.com/mapbox/carmen/issues/633)
=> Space out2

index.js, scripts/carmen-index.js, test/bin.test.js, test/fixtures/tokens.js
In some circumstances it might be desirable to have the global tokens file passed into the carmen-index.js be a Javascript file that can dynamically construct a set of token replacements, rather than a simple JSON file. In the event that such a file is used, it needs to be properly run and the resulting token object retrieved.
=> Fix behavior of carmen-index.js if it receives a global tokens in the form of a JS file

lib/verifymatch.js, test/bin.test.js, test/fixtures/output.default.geojson, test/fixtures/output.dev.geojson, test/fixtures/output.reverse-dev.geojson, test/geocode-unit.address-alphanumeric.test.js, test/geocode-unit.address-format.test.js, test/geocode-unit.address-misc.test.js, test/geocode-unit.address-omitted.test.js, test/geocode-unit.cluster-vs-range.test.js, test/geocode-unit.dataterm.test.js, test/geocode-unit.index-limit.test.js, test/geocode-unit.jp-order.test.js, test/geocode-unit.localtext.test.js, test/geocode-unit.numeric.test.js, test/geocode-unit.promote-language.test.js, test/geocode-unit.promote-score.test.js, test/geocode-unit.proximity.test.js, test/geocode-unit.relevance.test.js, test/geocode-unit.strictloose.test.js, test/geocode-unit.tile-edge.test.js, test/geocode-unit.tokens.test.js
TL;DR I think it's time to remove the gappy/stacky penalties.
In `master` we apply a very slight penalty and a very slight bonus in these scenarios:
- If you search for something using text that gives it additional context, we give a slight bonus to that feature ("stacking")
- Example Query: "Atlanta Georgia"
- "Atlanta Georgia" (the place, region) gets a slight text relev bonus in comparison to
- "Atlanta Georgia's Best Beer Brewery" (the poi)
- If you search for something where the context is closer in hierarchy to the feature involved, it gets a higher bonus than a feature where the context is very far away in hierarchy
- Example Query: "100 Main Street United States" << `address <=> country` context distance is far
- Example Query: "100 Main Street Buffalo" << `address <=> place` …
=> Remove stacky, gappy penalties

lib/util/token.js, test/replace.test.js
When creating inverse token replacers for use at index time, the `geocoder_tokens` object can be mutated in a way such that the inverse tokens (which only should be used at index time) are included in the runtime token replacers.
Cloning the tokens object before adding inverse tokens avoids accidentally mutating a shared object.
* Clone tokens object when creating replacers
=> clone token object before creating replacers, don't mutate in place

lib/util/termops.js, lib/verifymatch.js, test/geocode-unit.address-numnum.test.js, test/termops.maskAddress.test.js
Ran into this debugging a wacky address query in Sweden:
```
115 39 Sweden
```
Can currently return something like 
```
115 115, 269 76 Torekov, Skåne län, Sweden
```
What's going on here where we end up with the house 115 on street 115 but no sign of 39 to be found?
- Query gets numtokenized and normalized to these two permutations: `## 115` `1## 39` (we always index the data with housenum first).
- `## 115` matches data
- On the way back out, the `maskAddress` is `11` (both term positions are potential house numbers) and maskAddress is called against the original _query_ which has tokens in this order `115 39`
- It snags the first housenum-like value, `115`
- And pairs it with the street that's been found, `115`
And so we end up with `115 115`.
Make `maskAddress` a bit smarter by …
=> The Numnum Bug

lib/util/termops.js, test/geocode-unit.address-format.test.js, test/geocode-unit.order.test.js, test/termops.getIndexableText.test.js
In `carmen@master` we index an address feature with house numbers like this:
```
1.0 ## main st
0.8 main st
```
Where the phrase variant without the house number gets a fixed `0.2` relevance penalty. This would be conceptually fine if all `main st` features in the world had house numbers, but in actuality some data has address features that actually have no house numbers associated with them. This creates a weird imbalance where these features actually get a strong relevance bonus in comparison:
```
// feature A, has house numbers
1.0 ## main st
0.8 main st
// feature B, has no house numbers
1.0 main st
```
This branch treats house num-less features all equally in terms of relevance, allowing you to search for just a street name with much more reliable results.
```
// feature A, has house …
```
=> Index streets (with no housenum) with full relevance

lib/constants.js, lib/spatialmatch.js, lib/util/proximity.js, lib/verifymatch.js, package-lock.json, package.json, test/geocode-unit.proximity-polygon.test.js, test/proximity.scoredist.test.js
- Updates to carmen-cache@0.18.5 (https://github.com/mapbox/carmen-cache/pull/110)
- Switches hardcoded proximity radius value to a constant that is synced with carmen-cache
- Tweaks proximity heuristics in carmen to better surface low scored features when nearby but respect massively scored features far away (2 orders of magnitude seems to be the right heuristic)
=> carmen-cache@0.18.5

README.md
@mtmail helpfully pointed out that this function isn't a part of Carmen's API in #439  
=> Remove Non-existent Function from README

lib/pure/addresscluster.js, lib/verifymatch.js, test/address.test.js, test/geocode-unit.duplicate-address.test.js
At present, if an address cluster contains multiple entries for a single address number, only one of them is considered in verifymatch. This PR alters the address cluster logic to return an array rather than a single point, of all matching numbers, so that verifymatch can consider any of them as potential responses.
Note that the deduplication mechanism that runs before results are returned will still collapse down to a single response if the duplicates end up having identical `place_name` values. There are a couple of circumstances where this change is still important, though:
* when a bbox excludes the value that would otherwise have been the one arbitrarily chosen as the response (in current production you get no results in this circumstance)
* when other layers in the stack end up …
=> Support duplicate address numbers in address clusters in forward queries

package.json
carmen-merge missing from bin dependencies. 
=> add carmen-merge a remergence

carmen-geojson.md
Proposed new spec for routable_point feature as described in #674 
I have a few open questions:
1. Not sure if it makes sense for routable_point to be a top-level key with the other carmen keys (in addition to standard GeoJSON), or if it should be nested under properties. I have it here as a top-level key because it seems to be the most consistent with the way things are done now.  It seems that as it is now, relevant, standardized location data is all top-level (center, bbox, etc), and properties seem to be non-standardized byproducts of data sources. Adding it top-level will mean a bigger change to the Carmen spec (and more deviation from standard GeoJSON), but hopefully adding properties shouldn't break any existing functionality. Also, are there other use-cases where information like …
=> Add documentation for routable_point for Carmen GeoJSON

lib/geocode.js, test/geocode-unit.types.test.js
Type filter validation is subtly broken. The current code for checking the validity of users' requested type filters look like this:
```
if (options.types) {
if (!Array.isArray(options.types) || options.types.length < 1)
return callback(errcode('options.types must be an array with at least 1 type', 'EINVALID'));
var l = options.types.length;
var acceptableTypes = Object.keys(geocoder.bytype).concat(Object.keys(geocoder.bysubtype));
while (l--) {
if (acceptableTypes.indexOf(options.types[l]) === -1) {
return callback(errcode('Type "' + options.types[l] + '" is not a known type. Must be one of: ' + acceptableTypes.join(', '), 'EINVALID'));
} else {
//remove any cases like poi and poi.landmark
var subtypeAndTypeExist = geocoder.bytype[options.types[l]] && …
```
=> Busted type filtering

lib/context.js, lib/pure/routablepoint.js, lib/util/ops.js, lib/verifymatch.js, package.json, test/geocode-unit.address-routable-point.test.js, test/routablepoint.test.js
Starts adding routable point functionality to geocoding results and tests, as outlined in #676 and #675.
This implements it for forward geocoding only, and is still in progress towards creating a fully production-ready feature.
- Use Turf.js [nearest-point-on-line](https://github.com/Turfjs/turf/tree/master/packages/turf-nearest-point-on-line) to find the routable point
- Add routable_point attribute to geocoding results for forward geocoding
- Add unit tests and integration test for routable point functionality
=> Routablequest tests and functionality

lib/phrasematch.js, scripts/carmen.js
Currently, the country param only filters out features that are not in the requested country or countries relatively late in the process, in verifymatch. We end up doing a fair amount of work finding and sorting results from indexes that will have all their results thrown away at the end.
We can skip indexes that don't contain any features in the requested country earlier in the process in phrasematch to improve performance.
* When using the country param, don't consider phrasematch results from indexes that don't contain features in the requested country.
=> Skip irrelevant indexes earlier when using country param

scripts/carmen.js, test/bin.test.js
https://github.com/mapbox/carmen/pull/681 added support for `bbox` arguments from the carmen CLI. This fixes error handling for that change and adds tests to confirm it works as expected.
=> Fix bbox in scripts/carmen.js

lib/util/token.js, test/token.test.js
- Updates to token tests
- Refactor to avoid use of anon fxn
- Ensure all assertions are `result, expected`
- Add tests around per-index regex tokens (sweden)
*Bug Fix*
On the first pass of generating a `from:to` pair, the original `to` string would be mutated to include the numbered replacement groups referencing the word boundaries.
So `$1something` would be mutated to become `$1$2something$3`
If the diacritic removal code was run it then removed the diacritics from the `from` replacer and ran the `to` creator again. Since the `to` had been mutated by the first pass it would then incorrectly calculate the numbered replace groups. 
Fix: Avoid mutating the original `to` text, instead cloning on write.
=> Token concat

lib/util/ops.js, test/geocode-unit.matching-text.test.js
A customer requested the ability to have more insight into how synonyms are surfaced.
Ref: https://github.com/ingalls/pt2itp/pull/313
@apendleton rightly pointed out we already do this, but practical testing of the PT2ITP backed indexes showed the `matching_*` tags were not being output.
This PR adds support for waffle indexed features as a fallback.
=> Waffle Matching Places

lib/context.js, test/geocode-unit.ghost.test.js
"Ghost" features (typically alternate place names, denoted by a score of
-1) are excluded from a feature's context array unless they were
included in the original query. This allows an alternate place name to
returned if it was explicitly requested, but otherwise the default place
name will be used.
However, in situations where a query token matches both a ghost and a
non-ghost feature (for instance, a POI with the same name as a ghost
place within which it is located), we will return the first feature that
happens to be returned when querying the vector tile, which is
arbitrary and non-deterministic between indexer runs.
This adjusts the context builder to use a priority order:
1. Non-ghost features that match a query token
2. Ghost features that match a query token
3. Non-ghost features …
=> Prefer non-ghost features when building context

package.json, yarn.lock
@boblannon @aarthykc this PR updates your working branch to use the newly refactored carmen-cache from mapbox/carmen-cache#116 . Main change is just in package.json, but there was also some churn in `yarn.lock` that seems unrelated to us. Don't think there's anything to worry about, but feel free to review and then merge into your branch as you see fit.
=> Bump to carmen-cache@0.21.0

lib/util/termops.js, test/termops.maskAddress.test.js
A customer has reported that addresses for the Town of Oconomowoc, WI fail to geocode.
Per the town code: https://ecode360.com/15607678
```
§ 85-5 Numbering system.
A. One hundred numbers shall be assigned to each invisible block, regardless of discrepancies in block sizes. Properties on the north and east sides of streets shall bear even numbers, and properties on the south and west sides of streets shall bear odd numbers.
B. The number assigned to each property shall be composed of two parts. The first part, or street designation, shall be composed of a directional letter, "N," "S," "W," followed by the number of the appropriate block line.
C. The second part of the property number, the block and house designation, shall be composed of a directional letter followed by the number of the …
```
=> You wouldn't believe this address format!

lib/util/ops.js, test/geocode-unit.address-format.test.js
Dashes are used as a postal address delimiter in some countries (such as
Brazil, where it is used to separate the city and region components).
This adds display support for dash-separted address formats in the
place_name property.
This also fixes a pre-existing bug in geocode-unit.address-format.test.js that could cause features to persist across test closures.
- Allow dashes as format string delimiter
- add teardown within each test closure in geocode-unit.address-format.test.js
=> Add support for dashes in format string

.gitignore, package.json
I noticed that the `yarn run test` and `yarn run coverage` scripts only ran 42 tests, since it was only running test files that were directly in the /test directory (specifically `bin.test.js`). Now that the tests have been refactored and organized (yay! 🎉 ), they're nested. This PR updates the scripts to run all of the nested tests.
None, that's it!
=> Update test and coverage scripts to test everything in test directory

package.json, yarn.lock
The new version excludes unnecessary build tools which were
previously included in the published package.
Refs https://github.com/mapbox/carmen-cache/pull/121
- bump carmen-cache
=> carmen-cache@0.21.1

.gitignore, carmen-geojson.md, docs/api.md, lib/geocoder/geocode.js, lib/geocoder/ops.js, lib/geocoder/routablepoint.js, lib/geocoder/verifymatch.js, test/acceptance/geocode-unit.address-routable-point.test.js, test/unit/geocoder/routablepoint.test.js
The intention of this PR is to add an option to enable routable point functionality to release in beta without disturbing existing API users, and to make the response more explicit (return `null` for the points instead of returning nothing at all, if routable points are requested
=> [WIP] Be explicit

bin/carmen-index.js, lib/text-processing/remove-diacritics.js, package.json, test/acceptance/geocode-unit.unicode.test.js, test/unit/text-processing/diacritics.test.js
Carmen's current diacritical mark handling handles precomposed diacritical marks (those where a single unicode codepoint represents a letter with a diacritical mark) but not combining diacritics (those where the diacritical mark is a separate codepoint that follows an unmarked stand-alone letter). This PR adds a mechanism to strip combining marks to the diacritical mark stripper, but only applies it in circumstances where the diacritical mark is applied to an existing character, and not to ones where the mark stands alone in a query or token, to avoid unexpected behavior potentially resulting from the diacritical mark remover rendering a query, label, or token empty.
=> Combining diacritics

bench/contextVector.js, bin/carmen.js, lib/geocoder/context.js, lib/geocoder/geocode.js, test/unit/geocoder/context.test.js
In the previous version, for reverse geocoding, routable points were being calculated for all features marked as `geocoder_routable` in the source in `context.js`, regardless of whether the `routing` option was set. In the final response, `routable_points` wasn't returned because there was a check for `routing` in `ops.js`, but this meant it was doing the work of calculating the points for every reverse request.
This update passes the `routing` option through `context.js` to only calculate the points if `routing` is set to `true`.
=> Reverse routing

lib/indexer/dawg.js
In the DAWG utility functions `dump` and `dumpWithNormalizations`, there's a stage where we take all the phrases (which have been unique-ified by being turned into keys in a `Map`), sort them, and then insert them one by one lexicographically into the underlying DAWG builder structure. The DAWG requires that the entries by in order byte-wise, rather than character-wise, and we get them in that order by iterating over the map, converting them all into `Buffer`s (which can be sorted byte-wise) and adding them to an array, sorting the array, and then looping over it and converting them back to strings again for insertion.
Apparently, though, there are situations where this string -> buffer -> string transformation sequence is lossy, I think maybe because the input string is somehow invalid. …
=> Handle strange dawg phrase insertion bug

LICENSE.md
The copyright year is old (happy 2018!) and the license name isn't explicitly called out.
=> update copyright year and add license name

LICENSE.md
Badge not appearing after adding `BSD 2-Clause "Simplified" License`.
=> fix license name

package.json
This should avoid the security warning being seen in tests:
```
@mapbox/carmen 24.5.1
↳ @mapbox/mbtiles 0.9.0
↳ sqlite3 3.1.13
↳ node-pre-gyp 0.6.38
↳ hawk 3.1.3
↳ cryptiles 2.0.5
↳ boom 2.10.1
↳ hoek 2.16.3
```
An old version of node-sqlite3 was being used.
=> [security] upgrade node-mbtiles & node-sqlite3

package.json
This will solve this security warning, seen on circle:
```
deep-extend 0.4.2 has known vulnerabilities:  severity: low; summary: Prototype pollution attack, CVE: CVE-2018-3750; https://hackerone.com/reports/311333
@mapbox/carmen 24.5.1
↳ mapnik 3.7.2
↳ node-pre-gyp 0.6.39
↳ rc 1.2.6
↳ deep-extend 0.4.2
```
An old version of node-mapnik was being used.
=> [security] upgrade node-mapnik

.circleci/config.yml
This modifies the circle config by abstracting sections that can be re-used via variables in the steps.
I learned this from https://github.com/mapbox/mapbox-gl-native/blob/master/circle.yml and have previously applied this at https://github.com/mapbox/mapbox-tile-copy/blob/master/.circleci/config.yml.
The advantage of this approach is that it will prepare the config to easily start testing with another node version easily (without resorting to using a custom docker image, which is more work).
This PR also:
- remove a variety of apt-deps that were added in #715 but are unnessary
- removes the duplicated `export NVM_DIR=\"$HOME/.nvm\" && [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"` by pushing the variables into `$BASH_ENV` so that all bash shells will inherit the key info
cc …
=> Refactor circle config to set up for testing multiple node versions

lib/geocoder/phrasematch.js, lib/geocoder/spatialmatch.js, test/acceptance/geocode-unit.fuzzy.test.js
This PR builds on #722 to add a mechanism for penalizing relevance for inexact matches when fuzzy match is enabled. It does this by calculating something like a Levenshtein ratio (inspired by, but not exactly the same as, the `ratio` operation as defined in python-levenshtein; see inline comments for specifics), and then reducing the weight of the match in the phrasematch object by multiplying it by this ratio. It repeats this multiplication operation after stacks have been rebalanced in spatialmatch.
I've also rewritten the existing fuzzy match tests as their results have now changed in light of the new relevances, and added some address-specific tests as they use a different codepath and need to be tested separately.
Nope
=> Fuzzy relevance

lib/indexer/indexdocs.js, lib/text-processing/termops.js, test/unit/indexer/index.test.js, test/unit/indexer/indexdocs.test.js, test/unit/text-processing/termops.getMinimalIndexableText.test.js
This branch makes a couple of changes meant to simplify index-time computation and speed up builds a bit. Nothing here is earth-shattering, but should be incrementally useful.
Nope
=> Simplifications to text processing for indexing

lib/text-processing/closest-lang.js, test/acceptance/geocode-unit.language-flag.test.js, test/unit/text-processing/closest-lang.test.js
=> handle nonmatching text with hyphens

lib/geocoder/phrasematch.js, package.json, yarn.lock
The fuzzy search work that landed in #719 introduced the possibility for higher latency in some classes of queries. This PR restricts the circumstances in which fuzzy matching is applied to achieve better performance.
=> Fuzzy length limit

.circleci/config.yml
#723 refactored are Circle tests, and part of the refactor introduced `set +e` commands to several sequences of instructions in the pipeline. The effect of these commands was to cause the entire CI pipeline to show up as failed only if the last command in the sequence failed, rather than if any of them failed, so we were not properly enforcing linting (or, for that matter, tests 😨 ) -- only the step confirming that the benchmarks run was determining CI success or failure.
This branch fixes that problem, and I made two other temporary branches that I'll delete after merge of this one, https://github.com/mapbox/carmen/tree/break-linting-on-purpose and https://github.com/mapbox/carmen/tree/break-tests-on-purpose , to confirm that linting and tests, respectively, appropriately cause Circle …
=> Fix linting enforcement on Circle

package.json, test/acceptance/geocode-unit.localtext.test.js, test/acceptance/geocode-unit.promote-language.test.js, test/acceptance/geocode-unit.translation-noauto.test.js, yarn.lock
This PR switches to carmen-cache@reduce-x-language-penalty, which decreases the penalty applied to out-of-language matches in coalesce from 10% to 4%, and update tests accordingly for new, higher relevance values.
The motivation was newfound interactions between the previous penalty and new, lower penalties introduced as part of the fuzzy search push. This allowed for circumstances where fuzzy matches would beat correctly spelled matches that were out of language, and in testing this seemed not to conform with user expectations.
=> Switch to carmen-cache@reduce-x-language-penalty

lib/geocoder/ops.js, test/unit/geocoder/ops.test.js
`geocoder_format` template parsing relies in part on removing all instances of comma (`,`) from the template string. If format strings contain the arabic variant of the comma (`،` or U+060C), then template parsing is broken.  This PR removes that variant and fixes the parsing steps.
Here's a parse on a format template with normal commas:
```
[ 'place._name', 'region._name', 'country._name' ]
```
...and here's what it looks like when arabic comma is present:
```
[ 'place._name}،{region._name}،{country._name' ]
```
=> fix geocoder_format template parsing to handle presence of arabic comma

lib/geocoder/verifymatch.js, lib/util/proximity.js, test/unit/util/proximity.meanScore.test.js, test/unit/util/proximity.scoredist.test.js
This PR fixes proximity.scoredist.test.js unit tests to call the `scoredist` function with all required arguments. Previously, the tests only passed in the score and distance parameter, not the zoom or radius parameters, which meant the calculated `scoredist` value was always `NaN`. As part of that bug fix, we also moved the `meanScore` function, which calculates the geometric mean of carmen geojson features' `carmen:score`, to util/proximity.js and added unit tests.
=> Proximity test fix

CHANGELOG.md, package.json, test/unit/util/proximity.meanScore.test.js, test/unit/util/proximity.scoredist.test.js
Unit test updates as part of https://github.com/mapbox/carmen/issues/747, https://github.com/mapbox/carmen/issues/748, and https://github.com/mapbox/carmen/issues/749. This changes proximity.scoredist unit tests to store whatever is greater, `carmen:score` or the calculated `scoredist` in the `carmen:scoredist` property and sort by `carmen:scoredist`. This follows how verifymatch calculates `carmen:scoredist`:
https://github.com/mapbox/carmen/blob/f831f2dfc9eb965752939f5809b18315b38b7659/lib/geocoder/verifymatch.js#L200-L203
cc @aarthykc @apendleton @miccolis @boblannon
=> Calculate and sort by real scoredists in proximity.scoredist unit tests

lib/constants.js, lib/geocoder/geocode.js, lib/geocoder/phrasematch.js, lib/geocoder/spatialmatch.js, lib/geocoder/verifymatch.js, test/acceptance/geocode-unit.cutoffs.test.js, test/unit/geocoder/spatialmatch.stackable.test.js
Per #746, 
This allows users to toggle limits that have been currently hard coded for performance benefits. The defaults have been added to the `constants.js` file and are overriden if the user provides a value through the options object.
=> [first cut] parameterized cutoffs

bin/carmen.js, test/bin.test.js
This PR makes it possible to add `--fuzzyMatch` and `--autocomplete` when querying using the carmen CLI at `bin/carmen.js`
=> adding fuzzymatch and autocomplete cli params

lib/geocoder/phrasematch.js, lib/geocoder/spatialmatch.js, test/acceptance/geocode-unit.prox_match.test.js
#758 resulted in some changes in behavior for proximity-sensitive queries such that in some circumstances, the ideal response no longer made it above the 30-stack cutoff in spatialmatch. This PR introduces an additional hint for proximity queries to increase the odds that the right one makes it above the cutoff, and also fixes a bug I incidentally found along the way.
=> Use proximity point and index bboxes as an additional stack sort hint

lib/geocoder/geocode.js
At present we every index on every forward query even if we can't use those results because of a type filter (we rely on a later check in spatialmatch instead). This branch adds some more checks so we phrasematch less stuff.
=> Be smarter about what we phrasematch

index.js, lib/geocoder/ops.js, lib/indexer/indexdocs.js, lib/text-processing/termops.js, test/acceptance/geocode-unit.language-autopopulate.test.js, test/acceptance/geocode-unit.language-universal-categories.js, test/unit/indexer/indexdocs.test.js, test/unit/text-processing/termops.getIndexableText.test.js
Sometimes we have features where our data provider hasn't specified the language's text, but it can be reasonably inferred from a feature's country. This PR adds a fallback mechanism that allows indexing a feature's default text such that it won't be penalized at query time given searches in the language we think the text is in, even though it hasn't been explicitly specified.
It also more generally restructures the `getIndexableText` function, where the bulk of the work here is happening, to hopefully be a little easier to understand. In the previous version, the function had two nested inner functions it used to mutate the structures it was working it, which made the flow pretty tough to follow. It now proceeds in order from top to bottom. Oh, and tests.
Preliminary exploration of using …
=> Auto-populate language text from default text

CHANGELOG.md, index.js, lib/geocoder/verifymatch.js, lib/util/proximity.js, package.json, test/acceptance/geocode-unit.proximity-squishy.test.js, test/unit/geocoder/verifymatch.test.js, test/unit/util/proximity.relevanceScore.test.js, test/unit/util/proximity.scoredist.test.js
Ref https://github.com/mapbox/carmen/issues/771. First pass at creating a composite score with `relevance` _and_ `scoredist` when `proximity` is enabled rather than using `scoredist` as a tie breaker for `relevance`. The current implementation gives `relevance` a weight of 1 and `scoredist` a weight of 0.3. These thresholds are arbitrary; I chose them because they create a final score that  overcomes a single 4% penalty on an element in the stack when the feature doesn't have a `carmen:text_<language code>` property in the user-specified language. The final result is stored in the `carmen:relevance` property (we should probably revisit this naming) and is a value between 0 and 1.
cc @apendleton @aarthykc @boblannon @miccolis
=> Sort final results w/ proximity enabled based on relevance and score/proximity composite 

lib/geocoder/phrasematch.js, test/acceptance/geocode-unit.languageMode-universal.test.js
#592 added a flag for marking a whole index as containing all universal (not-language-specific text). We thought that meant matches in those indexes were not penalized for cross-language mismatch, but that turns out not to be what that flag currently does; instead, it affects whether or not such matches can be included in results for queries made with the `languageMade: strict` flag even if they're out-of-language. This PR makes it also do the thing we already thought it did.
=> Don't penalize matches in indexes with an index-wide universal text flag

package.json, yarn.lock
Pulls in newer carmen-cache with a much more recent rocksdb release, as well as some other carmen-cache changes from a pretty substantial refactor https://github.com/mapbox/carmen-cache/pull/132
* Newer carmen-cache.
=> Bump carmen-cache & get newer rocksdb

lib/geocoder/verifymatch.js, lib/util/proximity.js, package.json, test/acceptance/geocode-unit.proximity-polygon.test.js, test/acceptance/geocode-unit.proximity-squishy.test.js, test/acceptance/geocode-unit.scoredist.test.js, test/unit/util/proximity.relevanceScore.test.js, test/unit/util/proximity.scoredist.test.js, yarn.lock
* Pull in update to carmen-cache https://github.com/mapbox/carmen-cache/pull/139 which accounts for score when proximity scoring close results.
* Tighened the width of gaussian curved by factor of 3. Previously this overcompensated for the fact that carmen-cache was unlikely to return many relatively low scored results past 20-30 miles. New version of carmen-cache fixes this. 
* Rescaled distance and weight during proximity scoring. Previously both were put on a 1-11 scale. Now; distance is 1-10, score is 1-500. This is necessary because actual scores can vary huge amounts and minor difference would always lose out to distance.
* Fixed a bug (in `/lib/geocoder/verifymatch.js`) where the composite relevance + scoredist value was ignored during a sort if the `b` value was greater than `a`. …
=> Try new scoredist calculation in carmen-cache

lib/geocoder/verifymatch.js, test/acceptance/geocode-unit.address-alphanumeric.test.js
Ref https://github.com/mapbox/carmen/issues/809
cc @miccolis @aarthykc @apendleton
=> Don't interpret unit numbers as addresses

lib/geocoder/verifymatch.js, test/acceptance/geocode-unit.address-sort-interpolated.test.js, test/unit/geocoder/verifymatch.test.js
Ref https://github.com/mapbox/carmen/issues/821
This is a simple change but revealed some other behavior around how we handle interpolation and deduplication I'd like to dig into.
=> Preference non-interpolated address results

CHANGELOG.md
I forgot to write a Changelog entry when I released v27.1.0, which incorporates #813 and #817 . This PR adds that. It should be merged whenever someone next merges something and cuts a release.
no
=> Add changelog entry for v27.1.0

lib/geocoder/phrasematch.js, test/acceptance/geocode-unit.emoji.test.js
A funny interaction occurs between CJK tokenization and emoji removal. It seems that a query that ends in a CJK character followed by an emoji can lead to a set of tokenization/normalization steps that results in a token set in which the final token (where the emoji was originally) is an empty string instead. If instead the query is a Latin-letter word followed by a space followed by an emoji, there's no extra blank token, so apparently something about opting into the alternative tokenization path for CJK makes this happen. (Also: if there are Latin letters immediately next to the emoji, the last token is just those letters, with the emoji removed).
For non-address, indexes, which use windowed search, this presents a problem for autocomplete searches, because the empty string is a prefix …
=> Fix empty-phrasematch issue

lib/geocoder/addresscluster.js, test/acceptance/geocode-unit.address-properties.test.js
Tighten expectations around `null`/`undefined` properties in the address property passthrough code
Full explanation here: https://github.com/ingalls/pt2itp/pull/432#issue-262950290
This code flips the property passthrough code to iterate over `feat.properties.carmen:addressprops` and update the property instead of the current iteration over `feat.properties`
This is necessary as carmen does not allow storage of top level properties with a value of `null` or `undefined`
=> Override invert prop

lib/geocoder/verifymatch.js, test/acceptance/geocode-unit.address-intersections.test.js
We need to be able to differentiate between `street` results and `intersection` results as we promise in our api documentation that we will differentiate where possible
This introduces a flag that can be used upstream to differentiate between a street & intersection result
=> Intersection = True

lib/util/feature.js, test/unit/util/feature.putFeatures.test.js
Seeing a few fatal aborts because of "Invalid regular expression". If this function is just for checking the occurrence of a string, we should avoid using regexes. This PR replaces the regex approach with `indexOf`.
=> Fixes fatal aborts that occur because of Invalid regular expression 

lib/text-processing/termops.js, test/unit/text-processing/termops.numTokenize.test.js
This PR adds a new acceptable pattern for address numbers in order to support Russian korpus and stroenie numbers.  
| English | Russian | Abbreviations | Description |
|---|---|---|---|
| Corpus | корпус | k, кор, к  | Block number or substructure |
| Stroenie | строение | str, c, стр, с | Building, smaller than a block | 
That format variants that we're going to support are:
| parts | examples |
|---|---|
| number | 12 |
| number, korpus | 12к3 |
| number, stroenie | 12с4 |
| number, korpus, stroenie | 12к3с4 |
We're not going to support unit numbers, and `numTokenize` will remove everything after the first integer.
=> russian-style address numbers

docs/data-sources.md
Clarifies that not all properties listed in the [Document structure](https://github.com/mapbox/carmen/blob/c38c1190df8d4b7a403bdff238d50b34bd02a0b7/docs/data-sources.md#document-structure) table in the docs will be included depending on the index type. Specifically, `addressnumber` is only (optionally) present where `geocoder_address` is set to `1` for indexes that support address features.
cc @scottsfarley93
=> Clarify addressnumber property in docs

lib/geocoder/format-features.js, test/acceptance/geocode-unit.matching-text.test.js
The `matching_text` and `matching_place_name` properties are intended to surface feature names that most closely match the query, and are often used as the label for a feature in an api consumer's UI. Since categories are not distinguishable from synonyms, a feature that matched replace the primary feature name with the category in `matching_text` and `matching_place_name`, leading to confusing and indistinguishable results. For example a search for `coffee, washington, DC` would return `matching_text` of `coffee` and `matching_place_name` of `coffee, washington DC` for all features in the result set that matched the `coffee` category.
With this PR, if the matching text also matches a category configured on the index, the category will not replace the primary place name of a feature or …
=> No matching text categories

lib/geocoder/format-features.js, test/acceptance/geocode-unit.matching-text.test.js
Our matching text finder currently reruns part of the indexing process to generate all the indexable phrases from a feature to determine which source phrase produced a given query match. To avoid generating very large numbers of phrases for addresses due to address number expansion, it calls getIndexableText on a synthetic feature consisting only of the text field and not the address numbers, so when we *do* match a phrase that contains an address number, we won't generate it in getMatchingText, so we won't match it unless we strip the address number from the query side.
The current code attempts to do this: if on the first pass, we didn't find anything, we try again removing an initial address number from the beginning of the query; we recognize address numbers as zero or more numbers …
=> Fix matching_text for addresses

lib/text-processing/closest-lang.js, test/acceptance/geocode-unit.override.test.js
@miccolis identified a query that led to an error for one of our queries.
> TypeError: properties.carmen:text.split is not a function
> carmen/lib/text-processing/closest-lang.js:322:61
This section of the code is responsible for helping pick the correct language (if there are multiple) and formatting the place_name field for output. The error occurred as on of the text fields that was attempting to be processed was a numeric instead of a string.
The query was for an address level result with an `override:postcode` property. Generally, these properties are expected to be Strings, however there is currently no hard rule against these being numeric. This particular address was introduced via our JOSM=>Hecate Shim API as a result of a manual edit.
Since JOSM does not store or care about type …
=> Update test to ensure non-string input

lib/text-processing/termops.js, test/acceptance/geocode-unit.address-intersections.test.js, test/unit/geocoder/phrasematch.test.js, test/unit/text-processing/termops.intersectionPermutation.test.js
Refs #858 Presently just a sets of test that capture where a `&` -> `and`  works fine and where it's broken.
**Update** I think I've figured out the underlying issue - `intersectionPermutations` was generating a mask that used the `owners` of the tokens, this yielded a final mask that made sense against the actual user input. That seemed great at the time, but the problem is the surrounding code expects a local mask (one that doesn't account for cardinality changing replacements), and translates what it's given it into a final mask. This PR now generates a naive local mask and the surrounding code correctly translates it.
=> Properly handle ampersand replacement

CHANGELOG.md, lib/indexer/indexdocs.js, test/acceptance/geocode-unit.override.test.js
The code & tests appear to support string and numeric postcode overrides, but this isn't always the case. If a postcode override is numeric and the postcode separately matches the query the code to give the address result s relevance bump doesn't detect that they are the same and the postcode is likely to get sorted first.
* Cast any numeric `['carmen:addressprops']['override:postcode']` attributes to strings before indexing.
=> Support numeric input for postcode overrides

lib/geocoder/format-features.js, lib/indexer/index.js, lib/indexer/indexdocs.js, package.json, test/acceptance/geocode-unit.matching-text.test.js, test/unit/indexer/index.test.js, test/unit/indexer/indexdocs.test.js, yarn.lock
This PR contains the following work:
- Prefix store - As a part of https://github.com/mapbox/carmen-core/pull/41 & https://github.com/mapbox/carmen-core/issues/38, we need to be able to group all our data into precomputed buckets. With this change along with indexing all our data we create pre-computed groups of 1024 entries to enable a faster search experience during autocomplete queries.
- Fixes failing index builds because of the occurrence of the word  "constructor"  in our data. Builds failed with the following error: 
```
not ok 1 TypeError: gridPatch.has is not a function
```
=> Prefix work and carmen-core bug fixes

lib/geocoder/spatialmatch.js, lib/util/proximity.js, package.json, test/acceptance/geocode-unit.proximity-cutoff.test.js, test/unit/util/proximity.test.js, yarn.lock
This updates the format of the proximity option that the carmen-core version of coalesce requires.
=> Use new match opts format for coalesce proximity option

lib/geocoder/format-features.js, test/unit/geocoder/format-features.test.js
In #846, logic was added to dedupe results based on the text that a query matched in spatialmatch, combined with the geo context. This deduping logic is over-aggressive for address autocomplete queries that are very short, such as numerical-autocomplete or queries that have an address number + ~2 characters. It's possible for there to be several distinct features that match those queries that are in the same postcode, place and region.
This adds some logic to skip that extra deduping step if the address queries are particularly short.
=> Don't aggressively dedupe numerical autocomplete or short address query results

lib/geocoder/spatialmatch.js, lib/geocoder/verifymatch.js, lib/util/round-to.js, test/acceptance/geocode-unit.address-alphanumeric.test.js, test/acceptance/geocode-unit.address-format.test.js, test/acceptance/geocode-unit.address-preferred-order.test.js, test/acceptance/geocode-unit.backy.test.js, test/acceptance/geocode-unit.fuzzy.test.js, test/acceptance/geocode-unit.jp-order.test.js, test/acceptance/geocode-unit.order.test.js, test/acceptance/geocode-unit.override.test.js, test/acceptance/geocode-unit.promote-language.test.js, test/acceptance/geocode-unit.rebalance.test.js, test/acceptance/geocode-unit.relevance.test.js, test/unit/geocoder/spatialmatch.rebalance.test.js, test/unit/util/round-to.js
Our current rebalancing strategy (introduced by #448) assigns equal weight to all matching components, regardless of the number of words in each component, where before components where assigned weights based on the number of words they contained as a fraction of the total number of words in the query.
After having this in production for awhile, we now want to tweak this a little. For the "Martin Luther King Blvd, Seattle, Washington" example from #448, we still want Seattle, Washington to win -- if we can't actually align the feature with the city and state, we want the city and state together to win, because there are more components there. But for examples where there are actual ties (the same number of components in each possible result), #448 results in us instead disambiguating by …
=> Rebalance tweak

lib/util/feature.js, package.json, test/unit/util/feature.putFeatures.test.js, yarn.lock
#845 touched the `matchText` function in `lib/util/feature.js`, which tries to resolve ID collisions in fetch results from the feature table. That function was crashing, and we made it not crash, but it still didn't work; see #847 for more info. The plan was to fix this behavior with a series of changes in carmen-core and its equivalent carmen branch that would make ID collisions both less likely and easier to disambiguate, but that work has stalled due to unrelated carmen-core performance concerns.
This branch is a band-aid in the meantime. As noted in #847, the previous code almost never worked because it was broken with respect to case (input data was usually mixed case but equality tests were against lowercase cover text), and also didn't handle things like token replacement or other …
=> Use Levenshtein distance for coarse resolution of ID collisions

index.js, lib/geocoder/format-features.js, lib/util/feature.js, package.json, test/README.md, test/acceptance/geocode-unit.address-format.test.js, test/acceptance/geocode-unit.address-intersections.test.js, test/acceptance/geocode-unit.address-routable-point.test.js, test/acceptance/geocode-unit.address-street-fallback.test.js, test/acceptance/geocode-unit.backy-exemption.test.js, test/acceptance/geocode-unit.early-degen.test.js, test/acceptance/geocode-unit.emoji-bomb.test.js, test/acceptance/geocode-unit.jp-order.test.js, test/acceptance/geocode-unit.jp-passthrough.test.js, test/acceptance/geocode-unit.language-flag-reverse.test.js, test/acceptance/geocode-unit.language-flag.test.js, test/acceptance/geocode-unit.matching-text.test.js, test/acceptance/geocode-unit.multilanguage.test.js, test/acceptance/geocode-unit.override.test.js, test/acceptance/geocode-unit.relevance.test.js, test/acceptance/geocode-unit.text-trim.test.js, test/unit/geocoder/format-features.test.js, test/unit/geocoder/templating.test.js, yarn.lock
This PR replaces our home-grown templating system with an off-the-shelf that is more maintainable. After trying out a few different templating engine, we chose to go with Handlebars as our templating engine. Along with reworking/refactoring our templating engine, this PR also adds the following functionalities - 
1. Adds a mechanism for registering helper functions and making them available within templates to provide more customisable formatting options.
2. Allow feature specific template overrides - so for every feature if we have a `carmen:format`, we will prefer that format over the index format.
The way we select which template to apply to the feature is in the following order: 
- language-specific per-feature template - `carmen:format_<lang>`
- default per-feature template - …
=> New templating library

lib/geocoder/verifymatch.js, test/unit/geocoder/verifymatch.test.js
This PR applies a heuristic that if there are some results in the verified features that have higher spatialmatch relevance than the list of additional spatialmatch candidates, it is not worth it to load more features.
There was an attempt to keep track of the true partialNumberCount, but this resulted in repeatedly looping through the spatialmatch candidates after the first batch or two, only to load one more feature each time. As a result, the effective partialNumberLimit only applies to the first chunk of features loaded.
=> Stop early

lib/constants.js, lib/geocoder/verifymatch.js, test/unit/geocoder/verifymatch.test.js
The previous verifymatch stack limit increase and context backfill PR #879 allows for better results, but also is a significant performance decrease. Instead of reading data for 50 features at the beginning of verifymatch, this adds a similar backfill mechanism for feature loading, where additional features (on top of the initial 20) are only loaded if there aren't a full 20 verified features after verifying the first batch. Features are then loaded as needed, until there are either 20 verified features, or there have been a total of 50 loaded.
=> Feature backfill

lib/geocoder/addresscluster.js, lib/util/feature.js, test/unit/geocoder/address.properties.test.js, test/unit/geocoder/address.test.js
Queens uses a unique addressing system in which the address number follows the format `\d{2,3}-\d{2,3}` where the pre-hyphen number represents the major cross street/avenue number and the post-hyphen number represents the house number.  This ticket is the first half of supporting these addresses in Carmen.  This covers point lookups but not interpolation. Part of this will cause searches in Queens to be more lenient in the case of searching without a hyphen and the results will always return the hyphenated Queens style addresses. In addition, it lays out a base framework for adding other specific address styles.
=> Queens Address Matching

index.js, lib/indexer/indexdocs.js, lib/text-processing/termops.js, lib/text-processing/token.js, test/acceptance/geocode-unit.tokens.test.js, test/unit/text-processing/termops.getIndexablePhrases.test.js
From a recent address triage sprint we found out that 7% of the failures was because of `missing_input` which meant that the user didn't add information like the cardinal direction such as `NW`, `SW` or they left out the ordinal such as `3` instead of `3rd` or they didn't add the way type such as `street` or `Avenue`. 
Currently the way we identify and drop frequent words like the `way type` or the `cardinal directions` is by using a version of the [tf-idf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) logic. Given that we only index a few 1000 documents at a time, this method is not always great for identifying common words.
In the new indexing strategy the idea is that we're going to provide carmen with a list of frequent words which we will use while indexing. The idea is to use the …
=> Drop frequent words while indexing

lib/geocoder/spatialmatch.js, test/acceptance/geocode-unit.spatialmatch-stack-length.test.js
Issue: #849 
There is a stack length relevance penalty to prefer matches from fewer indexes over matches that span many indexes. This makes sense because it's likely that multiple words matching a single cover is more relevant than finding fewer words across many indexes.
A side effect of this was that a search for `San Francisco, CA` would return a poi called `San Francisco cable car` because the `san francisco` + `california` stack got an early relevance penalty and never made it into the final results. This PR reduces this penalty slightly.
The first approach changed the penalty from somewhere between .9 and 1 to be somewhere between .95 and 1, depending on the stack length. This meant that some pretty relevant fuzzy matches weren't making it to the final results because the stacks …
=> Less length penalty

.gitignore, lib/geocoder/context.js, package.json, yarn.lock
When upgrading from mapnik to VTQuery, it was unrealized at the time that mapnik did not support distance to polygons while VTQuery did.  This caused reverse geocode results return polygons that the point was not in.  This change returns to the original functionality which requires reverse geocoding points to be within the polygons it returns.  This does not affect behavior around point or line geometries.
* Update VTQuery
* Enable direct hit flag in VT Query
* Only direct hits on polygons will match
* Add .idea to .gitignore
=> VT Query Direct Hit Polygon

lib/geocoder/spatialmatch.js, lib/text-processing/termops.js, lib/util/feature.js, test/fixtures/output.dev.geojson, test/unit/text-processing/termops.logScale3Bit.test.js
Scores are encoded on a log scale between 1 and 7 for storage purposes. The scoredists coming out of carmen-cache are based on this log-encoded score. In spatialmatch, there is an attempt to "decode" the scoredist by accounting for the scorefactor of the data source. This isn't an exactly inverse mathmatical operation because the scoredist can factor in distance, in addition to the score.
Scoredists coming out of carmen-cache were getting "decoded" to a value that was always equal to 1 if the scorefactor of an index was 1. For example, matches with a scoredist of 1 coming out of coalesce and matches with a scoredist of 6 would both get "decoded" to a scoredist of 1 if the scorefactor of an index is 1.
This PR adds a small boost to the scorefactor to avoid losing the differentiation …
=> Scoredist decode hack

index.js, lib/indexer/indexdocs.js, lib/text-processing/termops.js, lib/text-processing/token.js, test/acceptance/geocode-unit.tokens.test.js, test/unit/text-processing/termops.getIndexablePhrases.test.js, test/unit/text-processing/termops.getIndexableText.test.js, test/unit/text-processing/token.replaceToken.test.js
A recent address triage process revealed that ~7% of the failures came from details missing data in input which means that the query left out details like the cardinal directions NW, SW), or way types (street, road etc) or ordinals. Out of the 7% of failures where the user failed to include details in the query, users most frequently left out ordinals like `th` in `7th street northwest`. A solution to this problem was to index both forms of the feature, one with the ordinal and one without at a reduced relevance. For example, say we have the following feature:
```
const address = {
id:1,
properties: {
'carmen:text':'4th Street Northwest',
'carmen:center':[0,0],
},
geometry: {
type: 'Point',
coordinates: [0,0]
}
};
```
The idea here is to index both `4th Street Northwest` as well as `4 …
=> Handle missing ordinals 

lib/geocoder/addresscluster.js
Dead code caused latency spikes due to unnecessary deep copies.
=> Bug Fix - Remove Dead Code Causing Performance Issues

lib/geocoder/verifymatch.js, lib/util/feature.js, lib/util/proximity.js, test/unit/util/feature.storableProperties.test.js, test/unit/util/proximity.scoredist.test.js
This PR makes it possible for a feature to have a custom proximity radius for calculating scoredist. This allows for surfacing important features, like airports, from farther away, without using a scoring adjustment that would increase the max score of an index. Increasing the max score of an index has wider ramifications, since the max score is used to encode and decode scores, and compare features across indexes. In addition, this doesn't change the global distribution of scores, it only affects the scoredist calculations when proximity is provided
=> Feature prox radius

index.js, lib/geocoder/geocode.js, lib/geocoder/phrasematch.js, lib/geocoder/spatialmatch.js, lib/indexer/index.js, package.json, yarn.lock
This is the companion PR to mapbox/carmen-core#72, which moves a bunch of fields from phrasematches into the gridstore type, and makes some other changes to how phrasematches are structured and coalesce is called.
No?
=> Gridstore opts

index.js, lib/geocoder/phrasematch.js, lib/geocoder/spatialmatch.js, lib/indexer/index.js, test/acceptance/geocode-unit.bmask.test.js, test/acceptance/geocode-unit.debug.test.js, test/acceptance/geocode-unit.geocoder_stack.test.js, test/acceptance/geocode-unit.multiconfig.test.js, test/unit/geocoder/phrasematch.test.js, test/unit/geocoder/spatialmatch.stackable.test.js
Changed bmask to be a Set instead of Arrays and commented/fixed a few tests to be able to run tests to completion. @apendleton mainly commented out phrasematch unit tests and spatialmatch tests (which have had the most invasive changes) in order to be able to run all tests.
- Uncomment tests and fix them in order to get all tests to pass
=> Change non_overlapping_indexes to be a set and not an array

index.js, lib/geocoder/phrasematch.js, lib/indexer/index.js, package.json, yarn.lock
This is the companion PR to https://github.com/mapbox/carmen-core/pull/76, which requires that the `idx` and `non_overlapping_indexes` properties, which had moved from phrasematches onto the gridstore object, be moved back to the phrasematch again. This was necessary because it turns out Carmen can reuse the same gridstore for multiple tilesets, and two different Carmen sources that share the same gridstore might not have the same idx.
=> Put idx and non_overlapping_indexes back how they were

lib/geocoder/phrasematch.js, package.json, test/unit/geocoder/phrasematch.test.js, yarn.lock
This PR is the companion to mapbox/carmen-core#89 . It switches to pointing at that gitsha, and also now passes in a `nearbyOnly` property in numerical-autocomplete cases. Turns out we used to want to flag exactly these same cases with a property called `extendedScan` that doesn't do anything in carmen-core anymore (carmen-cache used it and it's now ignored), so I just renamed that.
No
=> carmen-core@nearby-only

index.js, lib/indexer/index.js, package.json, test/acceptance/geocode-unit.address-partial-number.js, yarn.lock
This PR is the companion to mapbox/carmen-core#91 . It switches to pointing at that gitsha, and now calculates a zxy bounding box for each index at carmen start time, and passes that bounding box into the gridstore of the index at instantiation, so that it can be used in coalesce.
Currently this is PR'ed against nearby-only since it includes that branch's work as well, but I will probably retarget once that branch lands.
Also: currently for indexes whose bounds cross the antemeridian, a tile-oriented bounding box is calculated that includes all latitudes. It might be better to instead either add support for AM-crossing bounding boxes to carmen-core, or to add support for including multiple bounding boxes to carmen-core, and decompose an index's bounding box into per-hemisphere components …
=> switch to carmen-core@bbox-aware-coalesce

lib/geocoder/addresscluster.js, test/unit/geocoder/address.test.js
#896 refactored the mechanism by which addresses are identified in an address cluster to be returned, and somewhat altered the way multiple matches can be returned from the same query. We do some degree of partial matching, to ignore, e.g., added-on letters (so e.g., matching "12" when "12B" was requested). In the now-present logic, both exact and approximate matches are treated equally, and after later deduplication, sometimes partial matches can beat out perfect matches in the final results. This means on a block with addresses 1, 1A, 1B, 1C, etc., only the coordinates for "1" might be surfaceable.
The new logic assigns each prospective match a rank: 0 for perfect, >0 for some level of approximate, with higher numbers worse. As the cluster is processed, we keep track of the best rank …
=> Use only the best address matches

lib/geocoder/filter-sources.js, lib/geocoder/spatialmatch.js, test/acceptance/geocode-unit.address-alphanumeric.test.js, test/acceptance/geocode-unit.backy.test.js, test/acceptance/geocode-unit.cutoffs.test.js, test/acceptance/geocode-unit.debug.test.js, test/acceptance/geocode-unit.emoji.test.js, test/acceptance/geocode-unit.geocoder_stack.test.js, test/acceptance/geocode-unit.io-stack.test.js, test/acceptance/geocode-unit.near-alignment.test.js, test/acceptance/geocode-unit.rebalance.test.js
We had commented out a couple of tests during the early stages of the rewrite of stackable/coalesce given that we hadn't added any limits in places. Uncommenting some of the tests now that we've added some limits in place to throw away less relevant results. We're still pulling in a lot more matches than we did previously, so some tests still fail because of the number of candidates we're still considering. @apendleton would love a second set of eyes on this PR
cc @apendleton 
=> Uncomment tests

index.js, lib/geocoder/phrasematch.js, lib/indexer/index.js, lib/util/bbox.js, package.json, test/acceptance/geocode-unit.reverse-scoredist.test.js, test/acceptance/geocode-unit.zeroscore.test.js, yarn.lock
This PR has several changes designed to improve stackable/coalesce performance, specifically related to single-character autocomplete queries.
=> Decomposed bbox

lib/geocoder/phrasematch.js
With the new carmen-core, we saw that queries which are multi word and end with a single letter are particularly slow. This is because on the carmen side, for a single character like `S` it ends up prefix matching second, seventh etc. This ends up being very expensive especially for large/heavy indexes. This PR throws such matches especially for large indexes (zoom >=14) and makes sure that for a multi word query that ends in a single character, we throw away matches that aren't the single character.
@apendleton I think right now it has your decompose-bbox changes as well, does it make sense then to have it branched off of decomposed-bbox?
=> Multi word single character fix

lib/geocoder/format-features.js, test/acceptance/geocode-unit.format-override.test.js
#878 introduced a way for individual features to override their template for producing their `place_name` geocoder responses. It turns out there was a bug in the way this was implemented such that if a feature in the *context* of a result, rather than the result itself, had an overridden template, that template would be used to render the response even though it was for the wrong feature (for example, if you looked for an address and it had an overridden template on its postcode, the address would be rendered with the postcode's template, so you'd end up with a place name without an address in it).
While I was fixing that, I noticed some other tidbits we hadn't caught the first time around:
- if a feature had both a language-specific template and a generic one, we'd use the generic one …
=> Fix template selection with per-feature overrides

lib/geocoder/phrasematch.js, package.json, yarn.lock
This branch adds a tweak for speed with stackable/coalesce
Nope
=> Speed improvements for stackable coalesce

lib/geocoder/context.js, lib/geocoder/verifymatch.js, lib/util/feature.js, test/acceptance/geocode-unit.forward-geocode-override.test.js, test/acceptance/geocode-unit.reverse-only.test.js, test/acceptance/geocode-unit.score-dedupe.test.js
This PR fixes a bug where we want to preserve a feature with a higher score, when there are two features with identical text. Currently, we're not checking for the score and are throwing away features with score <= 0 if it shares identical text to another feature, however, we should only do so if there is a feature with a higher score as the comment 
> // Eliminate any score < 0 results if there are better-scored results
>  // with identical text.
suggests.
This PR also adds the ability to hide a feature from showing up in forward search as the top level feature while still allowing surfacing it as a part of reverse geocoding. It will also allow the feature to be a part of the context, just removing it from forward search only when it's the top level feature. 
=> Reverse only property, minor bug fix

.eslintrc.json, lib/geocoder/spatialmatch.js, lib/geocoder/verifymatch.js, package.json, test/acceptance/geocode-unit.override.test.js, test/acceptance/geocode-unit.promote-score.test.js, test/fixtures/output.dev.geojson, test/unit/geocoder/verifymatch.test.js
This branch adds a new variant of the squishy bonus. In the original version, we look for candidate results where the result feature has a name that is the same as a feature in its context, and boost that result (so if you look for "new york," "new york new york" gets a boost). It doesn't do anything, though, for cases where both of the nested features are in the context, so for example, "1 main st new york" might match either "1 main st" features in NYC, or in other cities in New York, with equal weight. The earlier gappy penalty would have helped to prefer the address-in-city examples, but as that's no longer in place (and can't really be introduced because it caused lots of weird collateral behavior), we're out of luck here, especially when the scores of the results are tied.
This …
=> Squishy context

lib/geocoder/addresscluster.js, test/unit/geocoder/address.test.js
For standard (non-Queens) address numbers, currently the two strategies we have in place to match the number from a query with the number in the address are exact matching, and matching of versions of each where all the non-numeric characters are stripped out (so, "7-1" becomes "71," and we can match that if "71" was queried). We've noticed a common pattern in Europe where address numbers might include some unit information, and queries might omit that information, so, "7-1" might get searched for as "7." Our current strategy doesn't handle that case.
This PR adds a third strategy, which is to only include all of the numeric characters until we encounter the first non-numeric one (so, for "7-1," we'd produce "7"). This strategy is lower-ranked than either of the first two strategies, so …
=> Better address number matching if unit numbers are present

lib/geocoder/addresscluster.js, test/unit/geocoder/address.test.js
#949 introduced a new way of matching address numbers in address clusters that had an unexpected interaction with a built-in cutoff in the address matcher in some circumstances.
OId logic, roughly:
- iterate through the address numbers in the cluster, and calculate a "match rank" for each that represented the quality of the match
- if a given number matched the query and had at least as good a rank as we'd seen so far, keep it
-  if the number had a *better* rank than any we'd seen so far, throw away all the earlier ones, and keep just this one (and any subsequent ones with at least as good a rank
- if at any point, the accumulated list of address numbers (all of which would have the same rank -- whatever the best rank we'd seen so far) reached 10 numbers long, return the list
The …
=> Fix addresscluster regression

index.js, lib/geocoder/format-features.js, lib/util/helpers.js, package.json, test/unit/geocoder/templating.test.js, test/unit/util/helpers.js, yarn.lock
#878 moved Carmen's templates to use Handlebars. This branch builds a little on that to make some template operations in Carmen consumers a bit easier.
Nope
=> Template helpers

lib/geocoder/phrasematch.js, lib/text-processing/termops.js, lib/text-processing/token.js, test/acceptance/geocode-unit.autocomplete-tokenized-final-term.test.js, test/acceptance/geocode-unit.tokens.test.js
This PR makes a change to how queries that end in word boundaries are handled. Previously, whitespace at the ends of queries was stripped, and other terminal word boundaries were ignored, which for autocomplete queries might mean that we might treat the final token in the query as being the prefix of a longer word, even though the user had an expressed an intent that that word was complete (by typing a space or other boundary character). We now preserve this terminal word boundary info, and if it's present, use the `WORD_BOUNDARY` prefix scanning mode instead of the regular prefix scanning mode in our fuzzy_phrase queries, which forces the final token to be treated as a complete word and limits phrase results accordingly.
=> Terminal word boundaries

lib/geocoder/verifymatch.js, test/acceptance/geocode-unit.score-dedupe.test.js
Deduplication occurs at several points in Carmen. There's a deduplication operation specific to ghost features that happens in verifymatch. Currently it takes place after we've done coarse spatial alignment in carmen-core, but before we've done fine spatial alignment in verifymatch. A corner case exists where a ghost feature and a non-ghost feature could share a label, and the ghost feature could get deduplicated away, and then after that, the non-ghost feature could get rejected because it fails fine spatial alignment, such that neither feature makes it into the final result set even though the ghost feature might have been fine, and might have been better than any remaining features.
This PR swaps the order of those operations, so that we deduplicate only after fine spatial alignment …
=> Move where the ghost feature dedup happens in verifymatch

.travis.yml, bin/carmen-index.js, index.js, lib/geocoder/phrasematch.js, lib/indexer/index.js, package.json, test/acceptance/geocode-unit.reverse-scoredist.test.js, test/unit/geocoder/context.test.js, test/unit/geocoder/phrasematch.test.js, test/unit/indexer/fuzzy.test.js, test/unit/indexer/indexdocs.test.js, test/unit/text-processing/token.replaceToken.test.js, yarn.lock
This PR makes Carmen compatible with Node 14.
=> Upgrade to Node 14

bin/carmen-index.js, package.json, test/acceptance/geocode-unit.relevance.test.js, test/bin.test.js
We use `nyc` to run coverage analysis in CI for Carmen. It intercepts imports of JS source files and instruments them for coverage. We optionally accept JS source files as command line arguments in our `carmen-index.js` process, and it turns out that something about doing this under `nyc` on Node 14 caused a segfault during runs. For #957, I added an explicit `process.exit(0)` at the end of the indexing process, which seemed to prevent the segfault. It now seems, however, that because we pass data from Carmen to subsequent indexing stages via STDOUT, this exit, while it takes place after all JS code has completed, can cause the process to terminate before the STDOUT buffer has been fully flushed, potentially resulting in features not being included in built tiles.
This branch rolls back …
=> Roll back explicit exit in carmen-index.js

lib/indexer/index.js
In some cases when reading metadata from mbtiles sources parameters that should be numeric, such as geocoder_coalesce_radius are converted to strings. This leads to errors like this when instantiating a GridStore:
TypeError: invalid type: string "400", expected f64
The root problem of parameters changing types still needs to be tracked down, but this approach mitigates the problem for now.
n/a
=> Force geocoder_coalesce_radius to be a number

index.js, lib/geocoder/phrasematch.js, lib/geocoder/spatialmatch.js, lib/util/bbox.js, package.json, test/unit/geocoder/phrasematch.test.js, yarn.lock
This PR pulls in the carmen-core work that enabled a `bounds` param for individual phrasematches: https://github.com/mapbox/carmen-core/pull/102.
This limits results fetched during coalesce to just those within the `bounds` attached to the phrasematch. This can be useful for indexes that have features from multiple stacks when the query contains stack filters - adding a bounds param ensures only candidates from the filtered stack are considered during spatialmatch.
- Checks for stack specific bounds on an index when there are stack filters, unions those bounds and attaches the resulting bbox to the phrasematch object.
=> Add bounds filter for individual phrasematches

CHANGELOG.md, docs/addresses.md, lib/geocoder/context.js, lib/geocoder/routablepoint.js, lib/geocoder/verifymatch.js, lib/util/feature.js, package.json, test/acceptance/geocode-unit.address-routable-point.test.js, test/unit/geocoder/routablepoint.test.js
This PR intends to make routable point a correctable properties from upstream, for both forward and backward search.
- Bump carmen version in downstream repos
=> Correctable routable point
