mapbox/carmen

bench/fixtures/lake-streetnames.txt
bench/geocode.js

Adds bench script for stress testing geocoding performance.

Bench geocode

---

carmen-geojson.md

Some notes on the format of carmen responses -- potentially spec/versioned in the future.

Add docs on carmen geojson format

---

lib/geocode.js
lib/spatialmatch.js
lib/util/ops.js
lib/verifymatch.js
scripts/carmen.js
scripts/grid.js
test/bin.test.js
test/geocode-unit.test.js
test/ops.test.js

Debug options [WIP]

---

lib/context.js
test/context.test.js

Fail on bad VT's

---

lib/context.js
lib/verifymatch.js
test/geocode-unit.test.js

Fixes https://github.com/mapbox/carmen/issues/227.
Going to put this through its paces before merging.

grouping v2

---

index.js
lib/spatialmatch.js
lib/verifymatch.js
package.json
test/geocode-unit.test.js

carmen-cache@0.2.0

---

lib/geocode.js
test/bin.test.js
test/fixtures/debug-1a.json
test/fixtures/debug-1b.json
test/fixtures/debug-3a.json
test/geocode-unit.test.js

Adds some extra goodies to `--debug` for tracking down problem queries.
cc @ingalls

(more) debug 

---

lib/geocode.js
package.json
test/bin.test.js
test/fixtures/debug-1a.json
test/fixtures/debug-1b.json
test/fixtures/debug-3a.json
test/geocode-unit.test.js

https://github.com/mapbox/carmen-cache/pull/17

carmen-cache@0.2.1

---

lib/verifymatch.js
test/geocode-unit.test.js

Prioritize address point results over interpolated

---

lib/context.js
test/geocode-unit.test.js

Ensure that when `addressitp` layers are above `address` layers the address point is returned.

Reverse course capt

---

lib/geocode.js
lib/verifymatch.js

Been a while since I've used these -- cleaned up to match recent refactors.

Better debug/dev stats

---

lib/util/termops.js
test/termops.termsWeighted.test.js

Prevents 0-weight terms when indexing.

Disallow weightless terms

---

index.js
lib/loadall.js
test/index.test.js

Testing this out IRL to see if it can help limit memory usage in low mem environments.

Add unloadall method for clearing caches

---

lib/context.js
test/context.test.js

Shaves a little off the top of https://github.com/mapbox/carmen/pull/264.

Save the ghosts

---

lib/util/termops.js
test/geocode-unit.dataterm.test.js
test/termops.getHousenumRange.test.js
test/termops.getIndexableText.test.js

Performance optimization to reduce phrase index cardinality.

Snap dataterm min/max to intervals of 1000

---

package.json
test/geocode-unit.backy.test.js

Support for non-strict ordered matching in setRelevance.

Use carmen-cache@0.4.1

---

lib/util/termops.js
test/termops.uniqPermutations.test.js

Fixes https://github.com/mapbox/carmen/issues/293.
cc @ingalls

Lone house

---

lib/analyze.js
lib/context.js
package.json
test/cache.test.js

- Updates to carmen-cache @ 0.6.0 for more conservative memory use
- Reduces vtile LRU cache size for high zoom sources

Memory use reduction

---

lib/geocode.js
test/geocode-unit.byid.test.js

Broke this as part of c4 refactor -- this adds a test and restores it to working condition.

Fix + test for by-id geocoding

---

lib/verifymatch.js

Unclear what conditions cause this. Catch the error and pass back to learn more.

Catch misuse

---

lib/util/addfeature.js
test/geocode-unit.address-format.test.js

Adds GeoJSON functionality to our unit tests as well as beginning the conversion to the new indexing format with `geocode-unit-address-format`
cc/ @yhahn @camilleanne

All you can eat

---

scripts/carmen.js
test/bin.test.js

Slightly pwned myself with an old linked carmen version. This will help combat this.

Add version output

---

lib/util/termops.js
lib/util/token.js
package.json
test/replace.test.js

@camilleanne here are the changes to use the cxx version of unidecode (though it should probably go onto npm at some point)

Doff thy name unidecode cxx

---

lib/geocode.js
scripts/carmen.js
test/geocode-unit.address-format.test.js
test/geocode-unit.index-context.test.js

adds an `indexes` property to result objects for forward and reverse geocodes

expose indexes

---

package.json

Updates node-locking for a key bugfix around error handling.
cc @emilymcafee @ingalls

locking@2.0.2

---

lib/verifymatch.js

Unsure of why this happens, but catch it when it does.

Play defense against mystery bug

---

README.md
index.js
lib/util/dictcache.js
test/dictcache.test.js

Allow 24 or 28 bit dictcache indexes. cc @apendleton

Make Dictcache size configurable

---

package.json
scripts/carmen-degenize.js
test/bin.carmen-degenize.test.js

@apendleton use like:
```
echo "Main Street" | carmen-degenize
```

Add carmen-degenize script

---

lib/util/dictcache.js
test/dictcache.test.js

And adds function for auto-calculating a reasonable dict size based on cardinality.

Make dictcache size anywhere between 24-32 bits

---

lib/geocode.js
lib/spatialmatch.js
lib/util/dictcache.js
test/geocode-unit.dict-collision.test.js

@yhahn when you get a chance, let me know if this looks okay.

Detect dictcache collisions and report them in .geocode

---

lib/context.js

Play defense against idx

---

package.json

Drop mmap dependency as it was only needed by bitcache

Drop mmap dependency

---

lib/verifymatch.js

Bad news bears when atm when this is not caught.

Guard against getFeatureByCover nulls

---

lib/util/addfeature.js
package.json

Pass stream argument into index Update fxn and then ingest geojson features returned.
Then vectorize the new GeoJSON features. This will allow a subsequent PR that indexes a MultiPoint but vectorizes individual Points.

Add streaming addfeature

---

package.json

Double carmen-cache

---

scripts/carmen-index.js

minor functionality change to restore better logging during indexes (both to the console and via surrounding tools).
cc @ingalls

restore status output to stderr

---

lib/util/addfeature.js
package.json

cc/ @mapsam @springmeyer @flippmoke 
refs https://github.com/mapbox/mapnik-swoop/pull/10

Point to mapnik v2_spec

---

lib/copy.js
lib/merge.js

Fixes bad stream end event -- `finish` is premature.

Use stream 'end' event

---

lib/util/dedupe.js
test/dedupe.test.js
test/fixtures/relev.json

Ensure relev is always sorted on output
cc/ @sbma44 @yhahn

Lightbult Conspiracy

---

index.js
test/geocode-unit.invalid-tokens.test.js

To check if tokens which have a space between them are global or generated per index. 
cc @yhahn, @arunasank

[ready]Validate if token replacer is global or per index

---

lib/geocode.js
test/geocode-unit.score.test.js

set relevance to 1 when querying by id

---

lib/constants.js
lib/geocode.js

This file would provide a source of truth for documentation

Move query constants into separate file

---

lib/context.js
lib/geocode.js
test/geocode-unit.range.test.js

Better handle index-level country ranges

New world order

---

lib/merge.js
package.json
test/cache.test.js

could use some advice on what to do with these errors. pairs with https://github.com/mapbox/carmen-cache/pull/56

[ready] clarify callback scope; throw on carmen-cache error

---

README.md
bench/contextVector.js
index.js
lib/context.js
lib/geocode.js
scripts/carmen.js
test/bin.test.js
test/context.test.js
test/geocode-unit.geocoder_type.test.js
test/geocode-unit.types.test.js

Allow filtering by subtype for reverse geocodes.
cc/ @sbma44

Subtype factory reverse

---

lib/context.js
lib/geocode.js
lib/verifymatch.js
test/context.test.js

A bunch of small changes that (I think) make the code clearer.

a bit of cleanup

---

ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md

Adds templates to help us communicate with other team members and carmen users.

Add Issue and PR templates :magic:

---

package.json

Refs https://github.com/mapbox/carmen-cache/pull/60.

carmen-cache@0.14.0

---

circle.yml

refs https://github.com/mapbox/cpp-internal/issues/11

Modernize libstdc++ install

---

CHANGELOG.md
package.json

Changelog changes and version bump for the recent rocksdb change
cc @apendleton, @yhahn

changelog changes and version bump

---

CHANGELOG.md
package.json

Changelog + new package for #604

changelog changes

---

lib/geocode.js
test/geocode-unit.index-context.test.js

idGeocode method currently doesn't return indexes for `scripts/carmen.js`

idGeocode should return indexes for cli tool

---

package.json

Ref: https://github.com/mapbox/api-geocoder/pull/1687

Updat mapnik

---

lib/util/addfeature.js
test/geocode-unit.address-misc.test.js

- Experimenting with Icelandic Unicode address names, was having trouble getting a feature indexed and then geocoded again.
- Adds a ITP/PT combined address feature
- Add support for ITP/PT combined feature in test indexer

Add icelandic language test

---

PULL_REQUEST_TEMPLATE.md

Adds `cc @mapbox/geocoding-gang` to PRs to make sure changes to our central hub of projects notify everyone by default.

Add gang cc to PR template

---

lib/util/token.js
test/replace.test.js

Addresses the word boundary issue that came up in #424 .

Fix replacer

---

CHANGELOG.md
lib/context.js
lib/indexer/indexdocs.js
lib/loader.js
lib/util/addfeature.js
lib/util/token.js
package.json
test/bin.test.js

Ensure it is easier for us to track updates to upstream packages that have switched to namespaced versions by switching over to use the new namespace.
This will allow tools like DavidDM to track updates again.

@mapbox Prefix

---

scripts/carmen.js

Allow carmen.js script to accept a function to create global tokens in addition to the traditional JSONM file. 
Ref: https://github.com/mapbox/geocoder-abbreviations/pull/13

Function Tokens

---

package.json

fix carmen-merge in bin dependecy

remergence-carmeanie

---

bin/carmen-analyze.js

Can't run .js without node hashbang

Added #!/usr/bin/env node

---

lib/geocoder/phrasematch.js
lib/geocoder/spatialmatch.js
test/acceptance/geocode-unit.geocoder_categories.test.js

PR is a attempt to fix #801 by setting a flag on phrasematch objects  instead of boosting relevence.
-  [x] needs down stream testing.

Category Matching flag

---

lib/text-processing/token.js
package.json
test/unit/text-processing/token.createReplacer.test.js
test/unit/text-processing/token.replaceToken.test.js
yarn.lock

PR removes the `xregexp` module and named regex support. We haven't used it for anything in quite a while.
Refs #515

Remove xregexp module

---

lib/text-processing/closest-lang.js
lib/text-processing/token.js
test/acceptance/geocode-unit.tokens.test.js
test/unit/text-processing/token.createReplacer.test.js
test/unit/text-processing/token.replaceToken.test.js

@miccolis these are the changes to your branch that were necessary to get carmen-indexer tests to pass. Will just comment inline with what each one does.

Boundaries plus regexes

---

README.md
docs/api.md

minor:  update docs from changes due to 8c0c54f2

---

lib/geocoder/context.js
package.json
yarn.lock

In certain situations, VTQuery can return too many results that we don't want.  So we are enabling skipping features we know we don't want in certain situations.

Vtquery filter

---

lib/geocoder/context.js
package.json
yarn.lock

This reverts commit 649088d5a87cb3689f4f80c97128cc9b21e405d2 decoupling the VT query work from the template work that shipped as a part of #880 and #878 respectively.

Revert "Merge pull request #880 from mapbox/vtquery-filter"

---

lib/geocoder/context.js
package.json
yarn.lock

Certain queries can be overwhelmed by data we know we don't want so we moved the filtering
into the VTQuery call to just not get this data in the first place.

Enable Selective Filtering in VTQuery

---

CHANGELOG.md
lib/geocoder/context.js

Adding missing JSDocs to carmen in geocoding/context.js

Add JSDocs

---

test/unit/geocoder/context.test.js

Polygons should only return if the point in reverse query is contained within the polygon.  This was fixed but now adding tests.
https://github.com/mapbox/carmen/issues/909

Add tests for near polygon misses

---

lib/geocoder/spatialmatch.js
package.json
test/acceptance/geocode-unit.address-alphanumeric.test.js
test/acceptance/geocode-unit.address-format.test.js
test/acceptance/geocode-unit.address-preferred-order.test.js
test/acceptance/geocode-unit.jp-order.test.js
test/acceptance/geocode-unit.near-alignment.test.js
test/acceptance/geocode-unit.order.test.js
test/acceptance/geocode-unit.override.test.js
test/acceptance/geocode-unit.promote-language.test.js
test/acceptance/geocode-unit.relevance.test.js
test/unit/geocoder/spatialmatch.rebalance.test.js
yarn.lock

Rebalancing was over reaching, so it was reigned back in.  This also cleared out a couple temporary changes that don't have the impact desired.

Redo rebalance

---

package.json
yarn.lock

Remove Codecov integration due to [security breach](https://about.codecov.io/security-update/?utm_medium=email&utm_source=marketo&ajs_uid=2753404&ajs_event=Clicked%20Email&mkt_tok=MzMyLUxWWC03NDEAAAF8dJ7iBYCuyxJ8oWMLVngaIxq86mqAk5xJLdfCd2z6goGkeS_KOy1qPSGUd7GXIP8pxRnMhuJpOya-fdsHOM-07Fp2Ko-17alTgpeVPHXd).

Remove codecov

---

CHANGELOG.md
docs/addresses.md
lib/geocoder/routablepoint.js
package.json
test/acceptance/geocode-unit.address-routable-point.test.js
test/unit/geocoder/routablepoint.test.js

Multiple routable support for address

Multiple routable support for address
